package com.zmap.zmap.clinic.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.JbPrepayChargeSyncModel;

@Mapper
public interface JbPrepayChargeSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String prepayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    int insert(JbPrepayChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    int insertSelective(JbPrepayChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    JbPrepayChargeSyncModel selectByPrimaryKey(String prepayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JbPrepayChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jb_prepay_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JbPrepayChargeSyncModel record);
    
    JbPrepayChargeSyncModel selectByHisPrimaryKey(JbPrepayChargeSyncModel record);
    int deleteByHisPrimaryKey(JbPrepayChargeSyncModel record);
}