package com.zmap.zmap.clinic.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM2DiagnoseSyncModel;
@Mapper
public interface ZmapClinicCM2DiagnoseSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String diagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    int insert(ZmapClinicCM2DiagnoseSyncModel record);

    ZmapClinicCM2DiagnoseSyncModel selectByHisPrimaryKey(String value);//根据his库的业务主键判断是否已存在
    int batchInsert(List<ZmapClinicCM2DiagnoseSyncModel> record);//批量插入
    int batchUpdate(List<ZmapClinicCM2DiagnoseSyncModel> record);//批量更新
    int updateClinicID();//update clinic_id
    int deleteByHisPrimaryKey(String value);
    int updateByHisPrimaryKey(ZmapClinicCM2DiagnoseSyncModel record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    int insertSelective(ZmapClinicCM2DiagnoseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    ZmapClinicCM2DiagnoseSyncModel selectByPrimaryKey(String diagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapClinicCM2DiagnoseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_diagnose
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapClinicCM2DiagnoseSyncModel record);
}