package com.zmap.zmap.clinic.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM2DrugUseSyncModel;

@Mapper
public interface ZmapClinicCM2DrugUseSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String drugUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    int insert(ZmapClinicCM2DrugUseSyncModel record);

    ZmapClinicCM2DrugUseSyncModel selectByHisPrimaryKey(String value);//根据his库的业务主键判断是否已存在
    int batchInsert(List<ZmapClinicCM2DrugUseSyncModel> record);//批量插入
    int batchUpdate(List<ZmapClinicCM2DrugUseSyncModel> record);//批量更新
    int updateClinicID();//update clinic_id
    int deleteByHisPrimaryKey(String value);
    int updateByHisPrimaryKey(ZmapClinicCM2DrugUseSyncModel record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    int insertSelective(ZmapClinicCM2DrugUseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    ZmapClinicCM2DrugUseSyncModel selectByPrimaryKey(String drugUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapClinicCM2DrugUseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_drug_use
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapClinicCM2DrugUseSyncModel record);
}