package com.zmap.zmap.clinic.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM1SyncModel;
import com.zmap.zmap.clinic.model.ZmapClinicCM2ChargeSyncModel;

@Mapper
public interface ZmapClinicCM2ChargeSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    int insert(ZmapClinicCM2ChargeSyncModel record);
    
    ZmapClinicCM2ChargeSyncModel selectByHisPrimaryKey(String value);//判断是否已存在
    int batchInsert(List<ZmapClinicCM2ChargeSyncModel> record);//批量插入
    int deleteByHisPrimaryKey(String value);//根据regcode删除
    int updateByHisPrimaryKey(ZmapClinicCM1SyncModel record);
    int batchUpdate(List<ZmapClinicCM2ChargeSyncModel> record);//批量更新
    int updateClinicID();//update clinic_id
    int updateClinicIDWithDate(String curDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    int insertSelective(ZmapClinicCM2ChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    ZmapClinicCM2ChargeSyncModel selectByPrimaryKey(String chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapClinicCM2ChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m2_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapClinicCM2ChargeSyncModel record);
}