package com.zmap.zmap.clinic.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM1SyncModel;


@Mapper
public interface ZmapClinicCM1SyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String clinicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    int insert(ZmapClinicCM1SyncModel record);
    ZmapClinicCM1SyncModel selectByHisPrimaryKey(String regCode);//判断是否已存在
    int batchInsert(List<ZmapClinicCM1SyncModel> record);//批量插入
    int batchUpdate(List<ZmapClinicCM1SyncModel> record);//批量更新
    int deleteByHisPrimaryKey(String value);
    int updateByHisPrimaryKey(ZmapClinicCM1SyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    int insertSelective(ZmapClinicCM1SyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    ZmapClinicCM1SyncModel selectByPrimaryKey(String clinicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapClinicCM1SyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_m1_clinics
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapClinicCM1SyncModel record);
    
    
    List<ZmapClinicCM1SyncModel> selectSumByDayClinics(HashMap params);
    
    List<HashMap<String,String>> selectClinicsSumByDept(HashMap params);
    
    List<HashMap<String,String>> selectClinicsSumByDeptDoctor(HashMap params);
    
}