package com.zmap.zmap.clinic.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM2MOrderSyncModel;

@Mapper
public interface ZmapClinicCM2MOrderSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String morderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    int insert(ZmapClinicCM2MOrderSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    int insertSelective(ZmapClinicCM2MOrderSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    ZmapClinicCM2MOrderSyncModel selectByPrimaryKey(String morderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapClinicCM2MOrderSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_c_m2_morder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapClinicCM2MOrderSyncModel record);
    ZmapClinicCM2MOrderSyncModel selectByHisPrimaryKey(String morderCode);
    int deleteByHisPrimaryKey(String morderCode);
}