package com.zmap.zmap.framework.base.model;

public class ZmapRPatientModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.patient_name
     *
     * @mbg.generated
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.marriage_status
     *
     * @mbg.generated
     */
    private String marriageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.drug_allergic_his
     *
     * @mbg.generated
     */
    private String drugAllergicHis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.insure_id
     *
     * @mbg.generated
     */
    private String insureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.medical_card_no
     *
     * @mbg.generated
     */
    private String medicalCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.case_book_no
     *
     * @mbg.generated
     */
    private String caseBookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.name_spell
     *
     * @mbg.generated
     */
    private String nameSpell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.english_name
     *
     * @mbg.generated
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.in_hos_no
     *
     * @mbg.generated
     */
    private String inHosNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.citizenship
     *
     * @mbg.generated
     */
    private String citizenship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.charge_type
     *
     * @mbg.generated
     */
    private String chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.contract_unit
     *
     * @mbg.generated
     */
    private String contractUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.home_tel
     *
     * @mbg.generated
     */
    private String homeTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.unit_tel
     *
     * @mbg.generated
     */
    private String unitTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.contact_man_name
     *
     * @mbg.generated
     */
    private String contactManName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.relation
     *
     * @mbg.generated
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.contact_addr
     *
     * @mbg.generated
     */
    private String contactAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.contact_postcode
     *
     * @mbg.generated
     */
    private String contactPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.is_vip
     *
     * @mbg.generated
     */
    private String isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.is_in_system
     *
     * @mbg.generated
     */
    private String isInSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.in_hos_from
     *
     * @mbg.generated
     */
    private String inHosFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.edu_background
     *
     * @mbg.generated
     */
    private String eduBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.race
     *
     * @mbg.generated
     */
    private String race;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.religion
     *
     * @mbg.generated
     */
    private String religion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.native_language
     *
     * @mbg.generated
     */
    private String nativeLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.second_language
     *
     * @mbg.generated
     */
    private String secondLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.certi_type
     *
     * @mbg.generated
     */
    private String certiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_patient.member_code
     *
     * @mbg.generated
     */
    private String memberCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.patient_id
     *
     * @return the value of zmap_r_patient.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.patient_id
     *
     * @param patientId the value for zmap_r_patient.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.patient_code
     *
     * @return the value of zmap_r_patient.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.patient_code
     *
     * @param patientCode the value for zmap_r_patient.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.patient_name
     *
     * @return the value of zmap_r_patient.patient_name
     *
     * @mbg.generated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.patient_name
     *
     * @param patientName the value for zmap_r_patient.patient_name
     *
     * @mbg.generated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.sex
     *
     * @return the value of zmap_r_patient.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.sex
     *
     * @param sex the value for zmap_r_patient.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.id_card
     *
     * @return the value of zmap_r_patient.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.id_card
     *
     * @param idCard the value for zmap_r_patient.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.birthday
     *
     * @return the value of zmap_r_patient.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.birthday
     *
     * @param birthday the value for zmap_r_patient.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.phone
     *
     * @return the value of zmap_r_patient.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.phone
     *
     * @param phone the value for zmap_r_patient.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.marriage_status
     *
     * @return the value of zmap_r_patient.marriage_status
     *
     * @mbg.generated
     */
    public String getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.marriage_status
     *
     * @param marriageStatus the value for zmap_r_patient.marriage_status
     *
     * @mbg.generated
     */
    public void setMarriageStatus(String marriageStatus) {
        this.marriageStatus = marriageStatus == null ? null : marriageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.addr
     *
     * @return the value of zmap_r_patient.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.addr
     *
     * @param addr the value for zmap_r_patient.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.drug_allergic_his
     *
     * @return the value of zmap_r_patient.drug_allergic_his
     *
     * @mbg.generated
     */
    public String getDrugAllergicHis() {
        return drugAllergicHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.drug_allergic_his
     *
     * @param drugAllergicHis the value for zmap_r_patient.drug_allergic_his
     *
     * @mbg.generated
     */
    public void setDrugAllergicHis(String drugAllergicHis) {
        this.drugAllergicHis = drugAllergicHis == null ? null : drugAllergicHis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.insure_id
     *
     * @return the value of zmap_r_patient.insure_id
     *
     * @mbg.generated
     */
    public String getInsureId() {
        return insureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.insure_id
     *
     * @param insureId the value for zmap_r_patient.insure_id
     *
     * @mbg.generated
     */
    public void setInsureId(String insureId) {
        this.insureId = insureId == null ? null : insureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.medical_card_no
     *
     * @return the value of zmap_r_patient.medical_card_no
     *
     * @mbg.generated
     */
    public String getMedicalCardNo() {
        return medicalCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.medical_card_no
     *
     * @param medicalCardNo the value for zmap_r_patient.medical_card_no
     *
     * @mbg.generated
     */
    public void setMedicalCardNo(String medicalCardNo) {
        this.medicalCardNo = medicalCardNo == null ? null : medicalCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.case_book_no
     *
     * @return the value of zmap_r_patient.case_book_no
     *
     * @mbg.generated
     */
    public String getCaseBookNo() {
        return caseBookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.case_book_no
     *
     * @param caseBookNo the value for zmap_r_patient.case_book_no
     *
     * @mbg.generated
     */
    public void setCaseBookNo(String caseBookNo) {
        this.caseBookNo = caseBookNo == null ? null : caseBookNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.sub_hospital_code
     *
     * @return the value of zmap_r_patient.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_r_patient.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.hospital_code
     *
     * @return the value of zmap_r_patient.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.hospital_code
     *
     * @param hospitalCode the value for zmap_r_patient.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.name_spell
     *
     * @return the value of zmap_r_patient.name_spell
     *
     * @mbg.generated
     */
    public String getNameSpell() {
        return nameSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.name_spell
     *
     * @param nameSpell the value for zmap_r_patient.name_spell
     *
     * @mbg.generated
     */
    public void setNameSpell(String nameSpell) {
        this.nameSpell = nameSpell == null ? null : nameSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.english_name
     *
     * @return the value of zmap_r_patient.english_name
     *
     * @mbg.generated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.english_name
     *
     * @param englishName the value for zmap_r_patient.english_name
     *
     * @mbg.generated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.in_hos_no
     *
     * @return the value of zmap_r_patient.in_hos_no
     *
     * @mbg.generated
     */
    public String getInHosNo() {
        return inHosNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.in_hos_no
     *
     * @param inHosNo the value for zmap_r_patient.in_hos_no
     *
     * @mbg.generated
     */
    public void setInHosNo(String inHosNo) {
        this.inHosNo = inHosNo == null ? null : inHosNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.citizenship
     *
     * @return the value of zmap_r_patient.citizenship
     *
     * @mbg.generated
     */
    public String getCitizenship() {
        return citizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.citizenship
     *
     * @param citizenship the value for zmap_r_patient.citizenship
     *
     * @mbg.generated
     */
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship == null ? null : citizenship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.nation
     *
     * @return the value of zmap_r_patient.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.nation
     *
     * @param nation the value for zmap_r_patient.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.identity
     *
     * @return the value of zmap_r_patient.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.identity
     *
     * @param identity the value for zmap_r_patient.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.charge_type
     *
     * @return the value of zmap_r_patient.charge_type
     *
     * @mbg.generated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.charge_type
     *
     * @param chargeType the value for zmap_r_patient.charge_type
     *
     * @mbg.generated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.contract_unit
     *
     * @return the value of zmap_r_patient.contract_unit
     *
     * @mbg.generated
     */
    public String getContractUnit() {
        return contractUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.contract_unit
     *
     * @param contractUnit the value for zmap_r_patient.contract_unit
     *
     * @mbg.generated
     */
    public void setContractUnit(String contractUnit) {
        this.contractUnit = contractUnit == null ? null : contractUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.postcode
     *
     * @return the value of zmap_r_patient.postcode
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.postcode
     *
     * @param postcode the value for zmap_r_patient.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.home_tel
     *
     * @return the value of zmap_r_patient.home_tel
     *
     * @mbg.generated
     */
    public String getHomeTel() {
        return homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.home_tel
     *
     * @param homeTel the value for zmap_r_patient.home_tel
     *
     * @mbg.generated
     */
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel == null ? null : homeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.unit_tel
     *
     * @return the value of zmap_r_patient.unit_tel
     *
     * @mbg.generated
     */
    public String getUnitTel() {
        return unitTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.unit_tel
     *
     * @param unitTel the value for zmap_r_patient.unit_tel
     *
     * @mbg.generated
     */
    public void setUnitTel(String unitTel) {
        this.unitTel = unitTel == null ? null : unitTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.contact_man_name
     *
     * @return the value of zmap_r_patient.contact_man_name
     *
     * @mbg.generated
     */
    public String getContactManName() {
        return contactManName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.contact_man_name
     *
     * @param contactManName the value for zmap_r_patient.contact_man_name
     *
     * @mbg.generated
     */
    public void setContactManName(String contactManName) {
        this.contactManName = contactManName == null ? null : contactManName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.relation
     *
     * @return the value of zmap_r_patient.relation
     *
     * @mbg.generated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.relation
     *
     * @param relation the value for zmap_r_patient.relation
     *
     * @mbg.generated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.contact_addr
     *
     * @return the value of zmap_r_patient.contact_addr
     *
     * @mbg.generated
     */
    public String getContactAddr() {
        return contactAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.contact_addr
     *
     * @param contactAddr the value for zmap_r_patient.contact_addr
     *
     * @mbg.generated
     */
    public void setContactAddr(String contactAddr) {
        this.contactAddr = contactAddr == null ? null : contactAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.contact_postcode
     *
     * @return the value of zmap_r_patient.contact_postcode
     *
     * @mbg.generated
     */
    public String getContactPostcode() {
        return contactPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.contact_postcode
     *
     * @param contactPostcode the value for zmap_r_patient.contact_postcode
     *
     * @mbg.generated
     */
    public void setContactPostcode(String contactPostcode) {
        this.contactPostcode = contactPostcode == null ? null : contactPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.contact_phone
     *
     * @return the value of zmap_r_patient.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.contact_phone
     *
     * @param contactPhone the value for zmap_r_patient.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.is_vip
     *
     * @return the value of zmap_r_patient.is_vip
     *
     * @mbg.generated
     */
    public String getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.is_vip
     *
     * @param isVip the value for zmap_r_patient.is_vip
     *
     * @mbg.generated
     */
    public void setIsVip(String isVip) {
        this.isVip = isVip == null ? null : isVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.create_date
     *
     * @return the value of zmap_r_patient.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.create_date
     *
     * @param createDate the value for zmap_r_patient.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.is_in_system
     *
     * @return the value of zmap_r_patient.is_in_system
     *
     * @mbg.generated
     */
    public String getIsInSystem() {
        return isInSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.is_in_system
     *
     * @param isInSystem the value for zmap_r_patient.is_in_system
     *
     * @mbg.generated
     */
    public void setIsInSystem(String isInSystem) {
        this.isInSystem = isInSystem == null ? null : isInSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.in_hos_from
     *
     * @return the value of zmap_r_patient.in_hos_from
     *
     * @mbg.generated
     */
    public String getInHosFrom() {
        return inHosFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.in_hos_from
     *
     * @param inHosFrom the value for zmap_r_patient.in_hos_from
     *
     * @mbg.generated
     */
    public void setInHosFrom(String inHosFrom) {
        this.inHosFrom = inHosFrom == null ? null : inHosFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.edu_background
     *
     * @return the value of zmap_r_patient.edu_background
     *
     * @mbg.generated
     */
    public String getEduBackground() {
        return eduBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.edu_background
     *
     * @param eduBackground the value for zmap_r_patient.edu_background
     *
     * @mbg.generated
     */
    public void setEduBackground(String eduBackground) {
        this.eduBackground = eduBackground == null ? null : eduBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.race
     *
     * @return the value of zmap_r_patient.race
     *
     * @mbg.generated
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.race
     *
     * @param race the value for zmap_r_patient.race
     *
     * @mbg.generated
     */
    public void setRace(String race) {
        this.race = race == null ? null : race.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.religion
     *
     * @return the value of zmap_r_patient.religion
     *
     * @mbg.generated
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.religion
     *
     * @param religion the value for zmap_r_patient.religion
     *
     * @mbg.generated
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.native_language
     *
     * @return the value of zmap_r_patient.native_language
     *
     * @mbg.generated
     */
    public String getNativeLanguage() {
        return nativeLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.native_language
     *
     * @param nativeLanguage the value for zmap_r_patient.native_language
     *
     * @mbg.generated
     */
    public void setNativeLanguage(String nativeLanguage) {
        this.nativeLanguage = nativeLanguage == null ? null : nativeLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.second_language
     *
     * @return the value of zmap_r_patient.second_language
     *
     * @mbg.generated
     */
    public String getSecondLanguage() {
        return secondLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.second_language
     *
     * @param secondLanguage the value for zmap_r_patient.second_language
     *
     * @mbg.generated
     */
    public void setSecondLanguage(String secondLanguage) {
        this.secondLanguage = secondLanguage == null ? null : secondLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.certi_type
     *
     * @return the value of zmap_r_patient.certi_type
     *
     * @mbg.generated
     */
    public String getCertiType() {
        return certiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.certi_type
     *
     * @param certiType the value for zmap_r_patient.certi_type
     *
     * @mbg.generated
     */
    public void setCertiType(String certiType) {
        this.certiType = certiType == null ? null : certiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_patient.member_code
     *
     * @return the value of zmap_r_patient.member_code
     *
     * @mbg.generated
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_patient.member_code
     *
     * @param memberCode the value for zmap_r_patient.member_code
     *
     * @mbg.generated
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }
}