package com.zmap.zmap.framework.base.model;

public class ZmapLFeeItemModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_id
     *
     * @mbg.generated
     */
    private String feeItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_class_code
     *
     * @mbg.generated
     */
    private String feeClassCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_class_name
     *
     * @mbg.generated
     */
    private String feeClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_type_code
     *
     * @mbg.generated
     */
    private String feeTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_type_name
     *
     * @mbg.generated
     */
    private String feeTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_code
     *
     * @mbg.generated
     */
    private String feeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_name
     *
     * @mbg.generated
     */
    private String feeItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.zmap_fee_item_code
     *
     * @mbg.generated
     */
    private String zmapFeeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.zmap_fee_item_name
     *
     * @mbg.generated
     */
    private String zmapFeeItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_size
     *
     * @mbg.generated
     */
    private String feeItemSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_unit
     *
     * @mbg.generated
     */
    private String feeItemUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.fee_item_price
     *
     * @mbg.generated
     */
    private String feeItemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.item_start_date
     *
     * @mbg.generated
     */
    private String itemStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.item_stop_date
     *
     * @mbg.generated
     */
    private String itemStopDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_fee_item.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_id
     *
     * @return the value of zmap_l_fee_item.fee_item_id
     *
     * @mbg.generated
     */
    public String getFeeItemId() {
        return feeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_id
     *
     * @param feeItemId the value for zmap_l_fee_item.fee_item_id
     *
     * @mbg.generated
     */
    public void setFeeItemId(String feeItemId) {
        this.feeItemId = feeItemId == null ? null : feeItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_class_code
     *
     * @return the value of zmap_l_fee_item.fee_class_code
     *
     * @mbg.generated
     */
    public String getFeeClassCode() {
        return feeClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_class_code
     *
     * @param feeClassCode the value for zmap_l_fee_item.fee_class_code
     *
     * @mbg.generated
     */
    public void setFeeClassCode(String feeClassCode) {
        this.feeClassCode = feeClassCode == null ? null : feeClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_class_name
     *
     * @return the value of zmap_l_fee_item.fee_class_name
     *
     * @mbg.generated
     */
    public String getFeeClassName() {
        return feeClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_class_name
     *
     * @param feeClassName the value for zmap_l_fee_item.fee_class_name
     *
     * @mbg.generated
     */
    public void setFeeClassName(String feeClassName) {
        this.feeClassName = feeClassName == null ? null : feeClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_type_code
     *
     * @return the value of zmap_l_fee_item.fee_type_code
     *
     * @mbg.generated
     */
    public String getFeeTypeCode() {
        return feeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_type_code
     *
     * @param feeTypeCode the value for zmap_l_fee_item.fee_type_code
     *
     * @mbg.generated
     */
    public void setFeeTypeCode(String feeTypeCode) {
        this.feeTypeCode = feeTypeCode == null ? null : feeTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_type_name
     *
     * @return the value of zmap_l_fee_item.fee_type_name
     *
     * @mbg.generated
     */
    public String getFeeTypeName() {
        return feeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_type_name
     *
     * @param feeTypeName the value for zmap_l_fee_item.fee_type_name
     *
     * @mbg.generated
     */
    public void setFeeTypeName(String feeTypeName) {
        this.feeTypeName = feeTypeName == null ? null : feeTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_code
     *
     * @return the value of zmap_l_fee_item.fee_item_code
     *
     * @mbg.generated
     */
    public String getFeeItemCode() {
        return feeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_code
     *
     * @param feeItemCode the value for zmap_l_fee_item.fee_item_code
     *
     * @mbg.generated
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode == null ? null : feeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_name
     *
     * @return the value of zmap_l_fee_item.fee_item_name
     *
     * @mbg.generated
     */
    public String getFeeItemName() {
        return feeItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_name
     *
     * @param feeItemName the value for zmap_l_fee_item.fee_item_name
     *
     * @mbg.generated
     */
    public void setFeeItemName(String feeItemName) {
        this.feeItemName = feeItemName == null ? null : feeItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.zmap_fee_item_code
     *
     * @return the value of zmap_l_fee_item.zmap_fee_item_code
     *
     * @mbg.generated
     */
    public String getZmapFeeItemCode() {
        return zmapFeeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.zmap_fee_item_code
     *
     * @param zmapFeeItemCode the value for zmap_l_fee_item.zmap_fee_item_code
     *
     * @mbg.generated
     */
    public void setZmapFeeItemCode(String zmapFeeItemCode) {
        this.zmapFeeItemCode = zmapFeeItemCode == null ? null : zmapFeeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.zmap_fee_item_name
     *
     * @return the value of zmap_l_fee_item.zmap_fee_item_name
     *
     * @mbg.generated
     */
    public String getZmapFeeItemName() {
        return zmapFeeItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.zmap_fee_item_name
     *
     * @param zmapFeeItemName the value for zmap_l_fee_item.zmap_fee_item_name
     *
     * @mbg.generated
     */
    public void setZmapFeeItemName(String zmapFeeItemName) {
        this.zmapFeeItemName = zmapFeeItemName == null ? null : zmapFeeItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.sub_hospital_code
     *
     * @return the value of zmap_l_fee_item.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_l_fee_item.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.hospital_code
     *
     * @return the value of zmap_l_fee_item.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.hospital_code
     *
     * @param hospitalCode the value for zmap_l_fee_item.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_size
     *
     * @return the value of zmap_l_fee_item.fee_item_size
     *
     * @mbg.generated
     */
    public String getFeeItemSize() {
        return feeItemSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_size
     *
     * @param feeItemSize the value for zmap_l_fee_item.fee_item_size
     *
     * @mbg.generated
     */
    public void setFeeItemSize(String feeItemSize) {
        this.feeItemSize = feeItemSize == null ? null : feeItemSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_unit
     *
     * @return the value of zmap_l_fee_item.fee_item_unit
     *
     * @mbg.generated
     */
    public String getFeeItemUnit() {
        return feeItemUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_unit
     *
     * @param feeItemUnit the value for zmap_l_fee_item.fee_item_unit
     *
     * @mbg.generated
     */
    public void setFeeItemUnit(String feeItemUnit) {
        this.feeItemUnit = feeItemUnit == null ? null : feeItemUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.fee_item_price
     *
     * @return the value of zmap_l_fee_item.fee_item_price
     *
     * @mbg.generated
     */
    public String getFeeItemPrice() {
        return feeItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.fee_item_price
     *
     * @param feeItemPrice the value for zmap_l_fee_item.fee_item_price
     *
     * @mbg.generated
     */
    public void setFeeItemPrice(String feeItemPrice) {
        this.feeItemPrice = feeItemPrice == null ? null : feeItemPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.item_start_date
     *
     * @return the value of zmap_l_fee_item.item_start_date
     *
     * @mbg.generated
     */
    public String getItemStartDate() {
        return itemStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.item_start_date
     *
     * @param itemStartDate the value for zmap_l_fee_item.item_start_date
     *
     * @mbg.generated
     */
    public void setItemStartDate(String itemStartDate) {
        this.itemStartDate = itemStartDate == null ? null : itemStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.item_stop_date
     *
     * @return the value of zmap_l_fee_item.item_stop_date
     *
     * @mbg.generated
     */
    public String getItemStopDate() {
        return itemStopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.item_stop_date
     *
     * @param itemStopDate the value for zmap_l_fee_item.item_stop_date
     *
     * @mbg.generated
     */
    public void setItemStopDate(String itemStopDate) {
        this.itemStopDate = itemStopDate == null ? null : itemStopDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_fee_item.remark
     *
     * @return the value of zmap_l_fee_item.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_fee_item.remark
     *
     * @param remark the value for zmap_l_fee_item.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}