package com.zmap.zmap.framework.base.model;

public class ZmapLAcctItemModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.acct_item_id
     *
     * @mbg.generated
     */
    private String acctItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.acct_item_code
     *
     * @mbg.generated
     */
    private String acctItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.parent_code
     *
     * @mbg.generated
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.acct_item_name
     *
     * @mbg.generated
     */
    private String acctItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.is_leaf
     *
     * @mbg.generated
     */
    private String isLeaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.rec_item_name
     *
     * @mbg.generated
     */
    private String recItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.m_record_item_name
     *
     * @mbg.generated
     */
    private String mRecordItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.drop_time
     *
     * @mbg.generated
     */
    private String dropTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_acct_item.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.acct_item_id
     *
     * @return the value of zmap_l_acct_item.acct_item_id
     *
     * @mbg.generated
     */
    public String getAcctItemId() {
        return acctItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.acct_item_id
     *
     * @param acctItemId the value for zmap_l_acct_item.acct_item_id
     *
     * @mbg.generated
     */
    public void setAcctItemId(String acctItemId) {
        this.acctItemId = acctItemId == null ? null : acctItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.acct_item_code
     *
     * @return the value of zmap_l_acct_item.acct_item_code
     *
     * @mbg.generated
     */
    public String getAcctItemCode() {
        return acctItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.acct_item_code
     *
     * @param acctItemCode the value for zmap_l_acct_item.acct_item_code
     *
     * @mbg.generated
     */
    public void setAcctItemCode(String acctItemCode) {
        this.acctItemCode = acctItemCode == null ? null : acctItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.parent_code
     *
     * @return the value of zmap_l_acct_item.parent_code
     *
     * @mbg.generated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.parent_code
     *
     * @param parentCode the value for zmap_l_acct_item.parent_code
     *
     * @mbg.generated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.acct_item_name
     *
     * @return the value of zmap_l_acct_item.acct_item_name
     *
     * @mbg.generated
     */
    public String getAcctItemName() {
        return acctItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.acct_item_name
     *
     * @param acctItemName the value for zmap_l_acct_item.acct_item_name
     *
     * @mbg.generated
     */
    public void setAcctItemName(String acctItemName) {
        this.acctItemName = acctItemName == null ? null : acctItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.is_leaf
     *
     * @return the value of zmap_l_acct_item.is_leaf
     *
     * @mbg.generated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.is_leaf
     *
     * @param isLeaf the value for zmap_l_acct_item.is_leaf
     *
     * @mbg.generated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.rec_item_name
     *
     * @return the value of zmap_l_acct_item.rec_item_name
     *
     * @mbg.generated
     */
    public String getRecItemName() {
        return recItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.rec_item_name
     *
     * @param recItemName the value for zmap_l_acct_item.rec_item_name
     *
     * @mbg.generated
     */
    public void setRecItemName(String recItemName) {
        this.recItemName = recItemName == null ? null : recItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.m_record_item_name
     *
     * @return the value of zmap_l_acct_item.m_record_item_name
     *
     * @mbg.generated
     */
    public String getmRecordItemName() {
        return mRecordItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.m_record_item_name
     *
     * @param mRecordItemName the value for zmap_l_acct_item.m_record_item_name
     *
     * @mbg.generated
     */
    public void setmRecordItemName(String mRecordItemName) {
        this.mRecordItemName = mRecordItemName == null ? null : mRecordItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.create_time
     *
     * @return the value of zmap_l_acct_item.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.create_time
     *
     * @param createTime the value for zmap_l_acct_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.drop_time
     *
     * @return the value of zmap_l_acct_item.drop_time
     *
     * @mbg.generated
     */
    public String getDropTime() {
        return dropTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.drop_time
     *
     * @param dropTime the value for zmap_l_acct_item.drop_time
     *
     * @mbg.generated
     */
    public void setDropTime(String dropTime) {
        this.dropTime = dropTime == null ? null : dropTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_acct_item.remark
     *
     * @return the value of zmap_l_acct_item.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_acct_item.remark
     *
     * @param remark the value for zmap_l_acct_item.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}