package com.zmap.zmap.framework.base.model;

public class ZmapLOperationModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.oper_id
     *
     * @mbg.generated
     */
    private String operId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.oper_code
     *
     * @mbg.generated
     */
    private String operCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.oper_name
     *
     * @mbg.generated
     */
    private String operName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.zmap_oper_code
     *
     * @mbg.generated
     */
    private String zmapOperCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.zmap_oper_name
     *
     * @mbg.generated
     */
    private String zmapOperName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.icd_code
     *
     * @mbg.generated
     */
    private String icdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.icd_name
     *
     * @mbg.generated
     */
    private String icdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.pinyin_code
     *
     * @mbg.generated
     */
    private String pinyinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.oper_type1_code
     *
     * @mbg.generated
     */
    private String operType1Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.oper_type2_code
     *
     * @mbg.generated
     */
    private String operType2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.is_serious
     *
     * @mbg.generated
     */
    private String isSerious;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_operation.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.oper_id
     *
     * @return the value of zmap_l_operation.oper_id
     *
     * @mbg.generated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.oper_id
     *
     * @param operId the value for zmap_l_operation.oper_id
     *
     * @mbg.generated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.oper_code
     *
     * @return the value of zmap_l_operation.oper_code
     *
     * @mbg.generated
     */
    public String getOperCode() {
        return operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.oper_code
     *
     * @param operCode the value for zmap_l_operation.oper_code
     *
     * @mbg.generated
     */
    public void setOperCode(String operCode) {
        this.operCode = operCode == null ? null : operCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.oper_name
     *
     * @return the value of zmap_l_operation.oper_name
     *
     * @mbg.generated
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.oper_name
     *
     * @param operName the value for zmap_l_operation.oper_name
     *
     * @mbg.generated
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.zmap_oper_code
     *
     * @return the value of zmap_l_operation.zmap_oper_code
     *
     * @mbg.generated
     */
    public String getZmapOperCode() {
        return zmapOperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.zmap_oper_code
     *
     * @param zmapOperCode the value for zmap_l_operation.zmap_oper_code
     *
     * @mbg.generated
     */
    public void setZmapOperCode(String zmapOperCode) {
        this.zmapOperCode = zmapOperCode == null ? null : zmapOperCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.zmap_oper_name
     *
     * @return the value of zmap_l_operation.zmap_oper_name
     *
     * @mbg.generated
     */
    public String getZmapOperName() {
        return zmapOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.zmap_oper_name
     *
     * @param zmapOperName the value for zmap_l_operation.zmap_oper_name
     *
     * @mbg.generated
     */
    public void setZmapOperName(String zmapOperName) {
        this.zmapOperName = zmapOperName == null ? null : zmapOperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.icd_code
     *
     * @return the value of zmap_l_operation.icd_code
     *
     * @mbg.generated
     */
    public String getIcdCode() {
        return icdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.icd_code
     *
     * @param icdCode the value for zmap_l_operation.icd_code
     *
     * @mbg.generated
     */
    public void setIcdCode(String icdCode) {
        this.icdCode = icdCode == null ? null : icdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.icd_name
     *
     * @return the value of zmap_l_operation.icd_name
     *
     * @mbg.generated
     */
    public String getIcdName() {
        return icdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.icd_name
     *
     * @param icdName the value for zmap_l_operation.icd_name
     *
     * @mbg.generated
     */
    public void setIcdName(String icdName) {
        this.icdName = icdName == null ? null : icdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.pinyin_code
     *
     * @return the value of zmap_l_operation.pinyin_code
     *
     * @mbg.generated
     */
    public String getPinyinCode() {
        return pinyinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.pinyin_code
     *
     * @param pinyinCode the value for zmap_l_operation.pinyin_code
     *
     * @mbg.generated
     */
    public void setPinyinCode(String pinyinCode) {
        this.pinyinCode = pinyinCode == null ? null : pinyinCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.oper_type1_code
     *
     * @return the value of zmap_l_operation.oper_type1_code
     *
     * @mbg.generated
     */
    public String getOperType1Code() {
        return operType1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.oper_type1_code
     *
     * @param operType1Code the value for zmap_l_operation.oper_type1_code
     *
     * @mbg.generated
     */
    public void setOperType1Code(String operType1Code) {
        this.operType1Code = operType1Code == null ? null : operType1Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.oper_type2_code
     *
     * @return the value of zmap_l_operation.oper_type2_code
     *
     * @mbg.generated
     */
    public String getOperType2Code() {
        return operType2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.oper_type2_code
     *
     * @param operType2Code the value for zmap_l_operation.oper_type2_code
     *
     * @mbg.generated
     */
    public void setOperType2Code(String operType2Code) {
        this.operType2Code = operType2Code == null ? null : operType2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.is_serious
     *
     * @return the value of zmap_l_operation.is_serious
     *
     * @mbg.generated
     */
    public String getIsSerious() {
        return isSerious;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.is_serious
     *
     * @param isSerious the value for zmap_l_operation.is_serious
     *
     * @mbg.generated
     */
    public void setIsSerious(String isSerious) {
        this.isSerious = isSerious == null ? null : isSerious.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.sub_hospital_code
     *
     * @return the value of zmap_l_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_l_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_operation.hospital_code
     *
     * @return the value of zmap_l_operation.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_operation.hospital_code
     *
     * @param hospitalCode the value for zmap_l_operation.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}