package com.zmap.zmap.framework.base.model;

public class ZmapRDoctorModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.doctor_id
     *
     * @mbg.generated
     */
    private String doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.zmap_dept_code
     *
     * @mbg.generated
     */
    private String zmapDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.job_title_code
     *
     * @mbg.generated
     */
    private String jobTitleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.job_title
     *
     * @mbg.generated
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.zmap_doctor_code
     *
     * @mbg.generated
     */
    private String zmapDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.zmap_doctor_name
     *
     * @mbg.generated
     */
    private String zmapDoctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_r_doctor.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.doctor_id
     *
     * @return the value of zmap_r_doctor.doctor_id
     *
     * @mbg.generated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.doctor_id
     *
     * @param doctorId the value for zmap_r_doctor.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.doctor_code
     *
     * @return the value of zmap_r_doctor.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.doctor_code
     *
     * @param doctorCode the value for zmap_r_doctor.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.dept_code
     *
     * @return the value of zmap_r_doctor.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.dept_code
     *
     * @param deptCode the value for zmap_r_doctor.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.zmap_dept_code
     *
     * @return the value of zmap_r_doctor.zmap_dept_code
     *
     * @mbg.generated
     */
    public String getZmapDeptCode() {
        return zmapDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.zmap_dept_code
     *
     * @param zmapDeptCode the value for zmap_r_doctor.zmap_dept_code
     *
     * @mbg.generated
     */
    public void setZmapDeptCode(String zmapDeptCode) {
        this.zmapDeptCode = zmapDeptCode == null ? null : zmapDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.status
     *
     * @return the value of zmap_r_doctor.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.status
     *
     * @param status the value for zmap_r_doctor.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.doctor_name
     *
     * @return the value of zmap_r_doctor.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.doctor_name
     *
     * @param doctorName the value for zmap_r_doctor.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.sex
     *
     * @return the value of zmap_r_doctor.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.sex
     *
     * @param sex the value for zmap_r_doctor.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.id_card
     *
     * @return the value of zmap_r_doctor.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.id_card
     *
     * @param idCard the value for zmap_r_doctor.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.birthday
     *
     * @return the value of zmap_r_doctor.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.birthday
     *
     * @param birthday the value for zmap_r_doctor.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.job_title_code
     *
     * @return the value of zmap_r_doctor.job_title_code
     *
     * @mbg.generated
     */
    public String getJobTitleCode() {
        return jobTitleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.job_title_code
     *
     * @param jobTitleCode the value for zmap_r_doctor.job_title_code
     *
     * @mbg.generated
     */
    public void setJobTitleCode(String jobTitleCode) {
        this.jobTitleCode = jobTitleCode == null ? null : jobTitleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.job_title
     *
     * @return the value of zmap_r_doctor.job_title
     *
     * @mbg.generated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.job_title
     *
     * @param jobTitle the value for zmap_r_doctor.job_title
     *
     * @mbg.generated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.sub_hospital_code
     *
     * @return the value of zmap_r_doctor.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_r_doctor.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.hospital_code
     *
     * @return the value of zmap_r_doctor.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.hospital_code
     *
     * @param hospitalCode the value for zmap_r_doctor.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.zmap_doctor_code
     *
     * @return the value of zmap_r_doctor.zmap_doctor_code
     *
     * @mbg.generated
     */
    public String getZmapDoctorCode() {
        return zmapDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.zmap_doctor_code
     *
     * @param zmapDoctorCode the value for zmap_r_doctor.zmap_doctor_code
     *
     * @mbg.generated
     */
    public void setZmapDoctorCode(String zmapDoctorCode) {
        this.zmapDoctorCode = zmapDoctorCode == null ? null : zmapDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.zmap_doctor_name
     *
     * @return the value of zmap_r_doctor.zmap_doctor_name
     *
     * @mbg.generated
     */
    public String getZmapDoctorName() {
        return zmapDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.zmap_doctor_name
     *
     * @param zmapDoctorName the value for zmap_r_doctor.zmap_doctor_name
     *
     * @mbg.generated
     */
    public void setZmapDoctorName(String zmapDoctorName) {
        this.zmapDoctorName = zmapDoctorName == null ? null : zmapDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_r_doctor.password
     *
     * @return the value of zmap_r_doctor.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_r_doctor.password
     *
     * @param password the value for zmap_r_doctor.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}