package com.zmap.zmap.framework.base.model;

public class ZmapLExamineModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_id
     *
     * @mbg.generated
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_class_code
     *
     * @mbg.generated
     */
    private String examClassCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_class_name
     *
     * @mbg.generated
     */
    private String examClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_type_code
     *
     * @mbg.generated
     */
    private String examTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_type_name
     *
     * @mbg.generated
     */
    private String examTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_code
     *
     * @mbg.generated
     */
    private String examCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.exam_name
     *
     * @mbg.generated
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    private String zmapExamCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.zmap_exam_name
     *
     * @mbg.generated
     */
    private String zmapExamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.unit_price
     *
     * @mbg.generated
     */
    private String unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_l_examine.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_id
     *
     * @return the value of zmap_l_examine.exam_id
     *
     * @mbg.generated
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_id
     *
     * @param examId the value for zmap_l_examine.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(String examId) {
        this.examId = examId == null ? null : examId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_class_code
     *
     * @return the value of zmap_l_examine.exam_class_code
     *
     * @mbg.generated
     */
    public String getExamClassCode() {
        return examClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_class_code
     *
     * @param examClassCode the value for zmap_l_examine.exam_class_code
     *
     * @mbg.generated
     */
    public void setExamClassCode(String examClassCode) {
        this.examClassCode = examClassCode == null ? null : examClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_class_name
     *
     * @return the value of zmap_l_examine.exam_class_name
     *
     * @mbg.generated
     */
    public String getExamClassName() {
        return examClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_class_name
     *
     * @param examClassName the value for zmap_l_examine.exam_class_name
     *
     * @mbg.generated
     */
    public void setExamClassName(String examClassName) {
        this.examClassName = examClassName == null ? null : examClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_type_code
     *
     * @return the value of zmap_l_examine.exam_type_code
     *
     * @mbg.generated
     */
    public String getExamTypeCode() {
        return examTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_type_code
     *
     * @param examTypeCode the value for zmap_l_examine.exam_type_code
     *
     * @mbg.generated
     */
    public void setExamTypeCode(String examTypeCode) {
        this.examTypeCode = examTypeCode == null ? null : examTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_type_name
     *
     * @return the value of zmap_l_examine.exam_type_name
     *
     * @mbg.generated
     */
    public String getExamTypeName() {
        return examTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_type_name
     *
     * @param examTypeName the value for zmap_l_examine.exam_type_name
     *
     * @mbg.generated
     */
    public void setExamTypeName(String examTypeName) {
        this.examTypeName = examTypeName == null ? null : examTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_code
     *
     * @return the value of zmap_l_examine.exam_code
     *
     * @mbg.generated
     */
    public String getExamCode() {
        return examCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_code
     *
     * @param examCode the value for zmap_l_examine.exam_code
     *
     * @mbg.generated
     */
    public void setExamCode(String examCode) {
        this.examCode = examCode == null ? null : examCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.exam_name
     *
     * @return the value of zmap_l_examine.exam_name
     *
     * @mbg.generated
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.exam_name
     *
     * @param examName the value for zmap_l_examine.exam_name
     *
     * @mbg.generated
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.zmap_exam_code
     *
     * @return the value of zmap_l_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    public String getZmapExamCode() {
        return zmapExamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.zmap_exam_code
     *
     * @param zmapExamCode the value for zmap_l_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    public void setZmapExamCode(String zmapExamCode) {
        this.zmapExamCode = zmapExamCode == null ? null : zmapExamCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.zmap_exam_name
     *
     * @return the value of zmap_l_examine.zmap_exam_name
     *
     * @mbg.generated
     */
    public String getZmapExamName() {
        return zmapExamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.zmap_exam_name
     *
     * @param zmapExamName the value for zmap_l_examine.zmap_exam_name
     *
     * @mbg.generated
     */
    public void setZmapExamName(String zmapExamName) {
        this.zmapExamName = zmapExamName == null ? null : zmapExamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.unit_price
     *
     * @return the value of zmap_l_examine.unit_price
     *
     * @mbg.generated
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.unit_price
     *
     * @param unitPrice the value for zmap_l_examine.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice == null ? null : unitPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.sub_hospital_code
     *
     * @return the value of zmap_l_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_l_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_l_examine.hospital_code
     *
     * @return the value of zmap_l_examine.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_l_examine.hospital_code
     *
     * @param hospitalCode the value for zmap_l_examine.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}