package com.zmap.zmap.hospitalize.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.hospitalize.model.ZmapHospitalizeHM2ChargeSyncModel;
@Mapper
public interface ZmapHospitalizeHM2ChargeSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sickFeeFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    int insert(ZmapHospitalizeHM2ChargeSyncModel record);

    ZmapHospitalizeHM2ChargeSyncModel selectByHisPrimaryKey(String value);//根据his库的业务主键判断是否已存在
    int batchInsert(List<ZmapHospitalizeHM2ChargeSyncModel> record);//批量插入
    int batchUpdate(List<ZmapHospitalizeHM2ChargeSyncModel> record);//批量更新
    int updateHospitalizeID();//update hospitalizeid
    int deleteByHisPrimaryKey(String value);
    int updateByHisPrimaryKey(ZmapHospitalizeHM2ChargeSyncModel record);
    int updateHospitalizeIDWithDate(String curDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    int insertSelective(ZmapHospitalizeHM2ChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    ZmapHospitalizeHM2ChargeSyncModel selectByPrimaryKey(String sickFeeFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapHospitalizeHM2ChargeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapHospitalizeHM2ChargeSyncModel record);
}