package com.zmap.zmap.hospitalize.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.clinic.model.ZmapClinicCM1SyncModel;
import com.zmap.zmap.clinic.model.ZmapClinicCM2ChargeSyncModel;
import com.zmap.zmap.hospitalize.model.ZmapHospitalizeHM1HospitalizeSyncModel;

@Mapper
public interface ZmapHospitalizeHM1HospitalizeSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String inHosId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    int insert(ZmapHospitalizeHM1HospitalizeSyncModel record);

    ZmapHospitalizeHM1HospitalizeSyncModel selectByHisPrimaryKey(String value);//判断是否已存在
    int batchInsert(List<ZmapHospitalizeHM1HospitalizeSyncModel> record);//批量插入
    int deleteByHisPrimaryKey(String value);//根据regcode删除
    int updateByHisPrimaryKey(ZmapHospitalizeHM1HospitalizeSyncModel record);
    int batchUpdate(List<ZmapHospitalizeHM1HospitalizeSyncModel> record);//批量更新
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    int insertSelective(ZmapHospitalizeHM1HospitalizeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    ZmapHospitalizeHM1HospitalizeSyncModel selectByPrimaryKey(String inHosId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapHospitalizeHM1HospitalizeSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m1_hospitalize
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapHospitalizeHM1HospitalizeSyncModel record);
}