package com.zmap.zmap.hospitalize.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;


import com.zmap.zmap.hospitalize.model.ZmapHospitalizeHM2OperationSyncModel;

@Mapper
public interface ZmapHospitalizeHM2OperationSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String operFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    int insert(ZmapHospitalizeHM2OperationSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    int insertSelective(ZmapHospitalizeHM2OperationSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    ZmapHospitalizeHM2OperationSyncModel selectByPrimaryKey(String operFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapHospitalizeHM2OperationSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_operation
     *
     * @mbg.generated
     */
    
    ZmapHospitalizeHM2OperationSyncModel selectByHisPrimaryKey(String value);//判断是否已存在
    int batchInsert(List<ZmapHospitalizeHM2OperationSyncModel> record);//批量插入
    int deleteByHisPrimaryKey(String value);//根据regcode删除
    int updateHospitalizeID();//update hospitalizeid
    int updateByHisPrimaryKey(ZmapHospitalizeHM2OperationSyncModel record);
    int batchUpdate(List<ZmapHospitalizeHM2OperationSyncModel> record);//批量更新
    
    int updateByPrimaryKey(ZmapHospitalizeHM2OperationSyncModel record);
}