package com.zmap.zmap.hospitalize.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.hospitalize.model.ZmapHospitalizeHM2ExamineSyncModel;

@Mapper
public interface ZmapHospitalizeHM2ExamineSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    int insert(ZmapHospitalizeHM2ExamineSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    int insertSelective(ZmapHospitalizeHM2ExamineSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    ZmapHospitalizeHM2ExamineSyncModel selectByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapHospitalizeHM2ExamineSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_examine
     *
     * @mbg.generated
     */
    
    ZmapHospitalizeHM2ExamineSyncModel selectByHisPrimaryKey(String value);//判断是否已存在
    int batchInsert(List<ZmapHospitalizeHM2ExamineSyncModel> record);//批量插入
    int deleteByHisPrimaryKey(String value);//根据regcode删除
    int updateHospitalizeID();//update hospitalizeid
    int updateByHisPrimaryKey(ZmapHospitalizeHM2ExamineSyncModel record);
    int batchUpdate(List<ZmapHospitalizeHM2ExamineSyncModel> record);//批量更新
    
    int updateByPrimaryKey(ZmapHospitalizeHM2ExamineSyncModel record);
}