package com.zmap.zmap.hospitalize.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.hospitalize.model.ZmapHospitalizeHM2DrugUseSyncModel;

@Mapper
public interface ZmapHospitalizeHM2DrugUseSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String drugUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    int insert(ZmapHospitalizeHM2DrugUseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    int insertSelective(ZmapHospitalizeHM2DrugUseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    ZmapHospitalizeHM2DrugUseSyncModel selectByPrimaryKey(String drugUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapHospitalizeHM2DrugUseSyncModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_h_m2_drug_use
     *
     * @mbg.generated
     */
    
    ZmapHospitalizeHM2DrugUseSyncModel selectByHisPrimaryKey(String value);//判断是否已存在
    int batchInsert(List<ZmapHospitalizeHM2DrugUseSyncModel> record);//批量插入
    int deleteByHisPrimaryKey(String value);//根据regcode删除
    int updateHospitalizeID();//update hospitalizeid
    int updateByHisPrimaryKey(ZmapHospitalizeHM2DrugUseSyncModel record);
    int batchUpdate(List<ZmapHospitalizeHM2DrugUseSyncModel> record);//批量更新
    
    
    
    int updateByPrimaryKey(ZmapHospitalizeHM2DrugUseSyncModel record);
}