package com.zmap.zmap.clinic.model;

public class JbPrepayChargeSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.prepay_id
     *
     * @mbg.generated
     */
    private String prepayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.prepay_code
     *
     * @mbg.generated
     */
    private String prepayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.rec_type_code
     *
     * @mbg.generated
     */
    private String recTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.reg_seq
     *
     * @mbg.generated
     */
    private String regSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.rec_status
     *
     * @mbg.generated
     */
    private String recStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.mhome_page_code
     *
     * @mbg.generated
     */
    private String mhomePageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.pay_company
     *
     * @mbg.generated
     */
    private String payCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.company_bank
     *
     * @mbg.generated
     */
    private String companyBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.company_acct_no
     *
     * @mbg.generated
     */
    private String companyAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.settle_type_code
     *
     * @mbg.generated
     */
    private String settleTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.collect_time
     *
     * @mbg.generated
     */
    private String collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.oper_code
     *
     * @mbg.generated
     */
    private String operCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.oper_name
     *
     * @mbg.generated
     */
    private String operName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.agaist_amount
     *
     * @mbg.generated
     */
    private String agaistAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.settle_acct_code
     *
     * @mbg.generated
     */
    private String settleAcctCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.rec_amount
     *
     * @mbg.generated
     */
    private String recAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.change_amount
     *
     * @mbg.generated
     */
    private String changeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.prepay_type_code
     *
     * @mbg.generated
     */
    private String prepayTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jb_prepay_charge.settle_seq
     *
     * @mbg.generated
     */
    private String settleSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.prepay_id
     *
     * @return the value of jb_prepay_charge.prepay_id
     *
     * @mbg.generated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.prepay_id
     *
     * @param prepayId the value for jb_prepay_charge.prepay_id
     *
     * @mbg.generated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.prepay_code
     *
     * @return the value of jb_prepay_charge.prepay_code
     *
     * @mbg.generated
     */
    public String getPrepayCode() {
        return prepayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.prepay_code
     *
     * @param prepayCode the value for jb_prepay_charge.prepay_code
     *
     * @mbg.generated
     */
    public void setPrepayCode(String prepayCode) {
        this.prepayCode = prepayCode == null ? null : prepayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.rec_type_code
     *
     * @return the value of jb_prepay_charge.rec_type_code
     *
     * @mbg.generated
     */
    public String getRecTypeCode() {
        return recTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.rec_type_code
     *
     * @param recTypeCode the value for jb_prepay_charge.rec_type_code
     *
     * @mbg.generated
     */
    public void setRecTypeCode(String recTypeCode) {
        this.recTypeCode = recTypeCode == null ? null : recTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.reg_seq
     *
     * @return the value of jb_prepay_charge.reg_seq
     *
     * @mbg.generated
     */
    public String getRegSeq() {
        return regSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.reg_seq
     *
     * @param regSeq the value for jb_prepay_charge.reg_seq
     *
     * @mbg.generated
     */
    public void setRegSeq(String regSeq) {
        this.regSeq = regSeq == null ? null : regSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.rec_status
     *
     * @return the value of jb_prepay_charge.rec_status
     *
     * @mbg.generated
     */
    public String getRecStatus() {
        return recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.rec_status
     *
     * @param recStatus the value for jb_prepay_charge.rec_status
     *
     * @mbg.generated
     */
    public void setRecStatus(String recStatus) {
        this.recStatus = recStatus == null ? null : recStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.sickman_code
     *
     * @return the value of jb_prepay_charge.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.sickman_code
     *
     * @param sickmanCode the value for jb_prepay_charge.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode == null ? null : sickmanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.mhome_page_code
     *
     * @return the value of jb_prepay_charge.mhome_page_code
     *
     * @mbg.generated
     */
    public String getMhomePageCode() {
        return mhomePageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.mhome_page_code
     *
     * @param mhomePageCode the value for jb_prepay_charge.mhome_page_code
     *
     * @mbg.generated
     */
    public void setMhomePageCode(String mhomePageCode) {
        this.mhomePageCode = mhomePageCode == null ? null : mhomePageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.dept_code
     *
     * @return the value of jb_prepay_charge.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.dept_code
     *
     * @param deptCode the value for jb_prepay_charge.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.pay_company
     *
     * @return the value of jb_prepay_charge.pay_company
     *
     * @mbg.generated
     */
    public String getPayCompany() {
        return payCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.pay_company
     *
     * @param payCompany the value for jb_prepay_charge.pay_company
     *
     * @mbg.generated
     */
    public void setPayCompany(String payCompany) {
        this.payCompany = payCompany == null ? null : payCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.company_bank
     *
     * @return the value of jb_prepay_charge.company_bank
     *
     * @mbg.generated
     */
    public String getCompanyBank() {
        return companyBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.company_bank
     *
     * @param companyBank the value for jb_prepay_charge.company_bank
     *
     * @mbg.generated
     */
    public void setCompanyBank(String companyBank) {
        this.companyBank = companyBank == null ? null : companyBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.company_acct_no
     *
     * @return the value of jb_prepay_charge.company_acct_no
     *
     * @mbg.generated
     */
    public String getCompanyAcctNo() {
        return companyAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.company_acct_no
     *
     * @param companyAcctNo the value for jb_prepay_charge.company_acct_no
     *
     * @mbg.generated
     */
    public void setCompanyAcctNo(String companyAcctNo) {
        this.companyAcctNo = companyAcctNo == null ? null : companyAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.remark
     *
     * @return the value of jb_prepay_charge.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.remark
     *
     * @param remark the value for jb_prepay_charge.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.amount
     *
     * @return the value of jb_prepay_charge.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.amount
     *
     * @param amount the value for jb_prepay_charge.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.settle_type_code
     *
     * @return the value of jb_prepay_charge.settle_type_code
     *
     * @mbg.generated
     */
    public String getSettleTypeCode() {
        return settleTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.settle_type_code
     *
     * @param settleTypeCode the value for jb_prepay_charge.settle_type_code
     *
     * @mbg.generated
     */
    public void setSettleTypeCode(String settleTypeCode) {
        this.settleTypeCode = settleTypeCode == null ? null : settleTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.collect_time
     *
     * @return the value of jb_prepay_charge.collect_time
     *
     * @mbg.generated
     */
    public String getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.collect_time
     *
     * @param collectTime the value for jb_prepay_charge.collect_time
     *
     * @mbg.generated
     */
    public void setCollectTime(String collectTime) {
        this.collectTime = collectTime == null ? null : collectTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.oper_code
     *
     * @return the value of jb_prepay_charge.oper_code
     *
     * @mbg.generated
     */
    public String getOperCode() {
        return operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.oper_code
     *
     * @param operCode the value for jb_prepay_charge.oper_code
     *
     * @mbg.generated
     */
    public void setOperCode(String operCode) {
        this.operCode = operCode == null ? null : operCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.oper_name
     *
     * @return the value of jb_prepay_charge.oper_name
     *
     * @mbg.generated
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.oper_name
     *
     * @param operName the value for jb_prepay_charge.oper_name
     *
     * @mbg.generated
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.agaist_amount
     *
     * @return the value of jb_prepay_charge.agaist_amount
     *
     * @mbg.generated
     */
    public String getAgaistAmount() {
        return agaistAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.agaist_amount
     *
     * @param agaistAmount the value for jb_prepay_charge.agaist_amount
     *
     * @mbg.generated
     */
    public void setAgaistAmount(String agaistAmount) {
        this.agaistAmount = agaistAmount == null ? null : agaistAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.settle_acct_code
     *
     * @return the value of jb_prepay_charge.settle_acct_code
     *
     * @mbg.generated
     */
    public String getSettleAcctCode() {
        return settleAcctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.settle_acct_code
     *
     * @param settleAcctCode the value for jb_prepay_charge.settle_acct_code
     *
     * @mbg.generated
     */
    public void setSettleAcctCode(String settleAcctCode) {
        this.settleAcctCode = settleAcctCode == null ? null : settleAcctCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.rec_amount
     *
     * @return the value of jb_prepay_charge.rec_amount
     *
     * @mbg.generated
     */
    public String getRecAmount() {
        return recAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.rec_amount
     *
     * @param recAmount the value for jb_prepay_charge.rec_amount
     *
     * @mbg.generated
     */
    public void setRecAmount(String recAmount) {
        this.recAmount = recAmount == null ? null : recAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.change_amount
     *
     * @return the value of jb_prepay_charge.change_amount
     *
     * @mbg.generated
     */
    public String getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.change_amount
     *
     * @param changeAmount the value for jb_prepay_charge.change_amount
     *
     * @mbg.generated
     */
    public void setChangeAmount(String changeAmount) {
        this.changeAmount = changeAmount == null ? null : changeAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.prepay_type_code
     *
     * @return the value of jb_prepay_charge.prepay_type_code
     *
     * @mbg.generated
     */
    public String getPrepayTypeCode() {
        return prepayTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.prepay_type_code
     *
     * @param prepayTypeCode the value for jb_prepay_charge.prepay_type_code
     *
     * @mbg.generated
     */
    public void setPrepayTypeCode(String prepayTypeCode) {
        this.prepayTypeCode = prepayTypeCode == null ? null : prepayTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jb_prepay_charge.settle_seq
     *
     * @return the value of jb_prepay_charge.settle_seq
     *
     * @mbg.generated
     */
    public String getSettleSeq() {
        return settleSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jb_prepay_charge.settle_seq
     *
     * @param settleSeq the value for jb_prepay_charge.settle_seq
     *
     * @mbg.generated
     */
    public void setSettleSeq(String settleSeq) {
        this.settleSeq = settleSeq == null ? null : settleSeq.trim();
    }
}