package com.zmap.zmap.clinic.model;

public class ZmapClinicCM2ExamineSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_id
     *
     * @mbg.generated
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.clinic_id
     *
     * @mbg.generated
     */
    private String clinicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    private String examFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_time
     *
     * @mbg.generated
     */
    private String examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    private String examTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_code
     *
     * @mbg.generated
     */
    private String examCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.exam_result
     *
     * @mbg.generated
     */
    private String examResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_examine.iccard_code
     *
     * @mbg.generated
     */
    private String iccardCode;
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_id
     *
     * @return the value of zmap_m2_examine.exam_id
     *
     * @mbg.generated
     */
    
    private String zmapDeptCode;
    private String hospitalCode;
    private String subHospitalCode;
    
    
    
    public String getZmapDeptCode() {
		return zmapDeptCode;
	}

	public void setZmapDeptCode(String zmapDeptCode) {
		this.zmapDeptCode = zmapDeptCode== null ? null : zmapDeptCode.trim();
	}

	public String getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode== null ? null : hospitalCode.trim();
	}

	public String getSubHospitalCode() {
		return subHospitalCode;
	}

	public void setSubHospitalCode(String subHospitalCode) {
		this.subHospitalCode = subHospitalCode== null ? null : subHospitalCode.trim();
	}

	public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_id
     *
     * @param examId the value for zmap_m2_examine.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(String examId) {
        this.examId = examId == null ? null : examId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.clinic_id
     *
     * @return the value of zmap_m2_examine.clinic_id
     *
     * @mbg.generated
     */
    public String getClinicCode() {
        return clinicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.clinic_id
     *
     * @param clinicCode the value for zmap_m2_examine.clinic_id
     *
     * @mbg.generated
     */
    public void setClinicCode(String clinicCode) {
        this.clinicCode = clinicCode == null ? null : clinicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_flow_code
     *
     * @return the value of zmap_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    public String getExamFlowCode() {
        return examFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_flow_code
     *
     * @param examFlowCode the value for zmap_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    public void setExamFlowCode(String examFlowCode) {
        this.examFlowCode = examFlowCode == null ? null : examFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_time
     *
     * @return the value of zmap_m2_examine.exam_time
     *
     * @mbg.generated
     */
    public String getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_time
     *
     * @param examTime the value for zmap_m2_examine.exam_time
     *
     * @mbg.generated
     */
    public void setExamTime(String examTime) {
        this.examTime = examTime == null ? null : examTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.reg_code
     *
     * @return the value of zmap_m2_examine.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.reg_code
     *
     * @param regCode the value for zmap_m2_examine.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.patient_code
     *
     * @return the value of zmap_m2_examine.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.patient_code
     *
     * @param patientCode the value for zmap_m2_examine.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.doctor_code
     *
     * @return the value of zmap_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.doctor_code
     *
     * @param doctorCode the value for zmap_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.dept_code
     *
     * @return the value of zmap_m2_examine.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.dept_code
     *
     * @param deptCode the value for zmap_m2_examine.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_type_code
     *
     * @return the value of zmap_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    public String getExamTypeCode() {
        return examTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_type_code
     *
     * @param examTypeCode the value for zmap_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    public void setExamTypeCode(String examTypeCode) {
        this.examTypeCode = examTypeCode == null ? null : examTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_code
     *
     * @return the value of zmap_m2_examine.exam_code
     *
     * @mbg.generated
     */
    public String getExamCode() {
        return examCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_code
     *
     * @param examCode the value for zmap_m2_examine.exam_code
     *
     * @mbg.generated
     */
    public void setExamCode(String examCode) {
        this.examCode = examCode == null ? null : examCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.exam_result
     *
     * @return the value of zmap_m2_examine.exam_result
     *
     * @mbg.generated
     */
    public String getExamResult() {
        return examResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.exam_result
     *
     * @param examResult the value for zmap_m2_examine.exam_result
     *
     * @mbg.generated
     */
    public void setExamResult(String examResult) {
        this.examResult = examResult == null ? null : examResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_examine.iccard_code
     *
     * @return the value of zmap_m2_examine.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_examine.iccard_code
     *
     * @param iccardCode the value for zmap_m2_examine.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }
}