package com.zmap.zmap.clinic.model;

public class ZmapClinicCM2MOrderSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_id
     *
     * @mbg.generated
     */
    private String morderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_code
     *
     * @mbg.generated
     */
    private String morderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.related_code
     *
     * @mbg.generated
     */
    private String relatedCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.patient_name
     *
     * @mbg.generated
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.mhome_page_code
     *
     * @mbg.generated
     */
    private String mhomePageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.reg_code
     *
     * @mbg.generated
     */
    private String regSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_status
     *
     * @mbg.generated
     */
    private String morderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.treat_type_code
     *
     * @mbg.generated
     */
    private String treatTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.treat_code
     *
     * @mbg.generated
     */
    private String treatCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.treat_body_part
     *
     * @mbg.generated
     */
    private String treatBodyPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.fee_item_code
     *
     * @mbg.generated
     */
    private String feeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.days
     *
     * @mbg.generated
     */
    private String days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.single_use_volumn
     *
     * @mbg.generated
     */
    private String singleUseVolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.total_use_volumn
     *
     * @mbg.generated
     */
    private String totalUseVolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_content
     *
     * @mbg.generated
     */
    private String morderContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_special
     *
     * @mbg.generated
     */
    private String morderSpecial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.skin_test_result
     *
     * @mbg.generated
     */
    private String skinTestResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_dept_code
     *
     * @mbg.generated
     */
    private String execDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_freq
     *
     * @mbg.generated
     */
    private String execFreq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.freq_times
     *
     * @mbg.generated
     */
    private String freqTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.freq_interval
     *
     * @mbg.generated
     */
    private String freqInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.interval_time_unit
     *
     * @mbg.generated
     */
    private String intervalTimeUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_schedule
     *
     * @mbg.generated
     */
    private String execSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_type_code
     *
     * @mbg.generated
     */
    private String execTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_mark
     *
     * @mbg.generated
     */
    private String execMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_begin_time
     *
     * @mbg.generated
     */
    private String execBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.exec_end_time
     *
     * @mbg.generated
     */
    private String execEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.last_exec_time
     *
     * @mbg.generated
     */
    private String lastExecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_dept_code
     *
     * @mbg.generated
     */
    private String morderDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_doctor_code
     *
     * @mbg.generated
     */
    private String morderDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.morder_time
     *
     * @mbg.generated
     */
    private String morderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.proofread_nurse
     *
     * @mbg.generated
     */
    private String proofreadNurse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.proofread_time
     *
     * @mbg.generated
     */
    private String proofreadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.stop_doctor_code
     *
     * @mbg.generated
     */
    private String stopDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.stop_time
     *
     * @mbg.generated
     */
    private String stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.confirmed_stop_time
     *
     * @mbg.generated
     */
    private String confirmedStopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.confirmed_stop_nurse
     *
     * @mbg.generated
     */
    private String confirmedStopNurse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.check_mark
     *
     * @mbg.generated
     */
    private String checkMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.check_status
     *
     * @mbg.generated
     */
    private String checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.first_use_volumn
     *
     * @mbg.generated
     */
    private String firstUseVolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.over_use_volumn
     *
     * @mbg.generated
     */
    private String overUseVolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.combined_item_code
     *
     * @mbg.generated
     */
    private String combinedItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.fomula_code
     *
     * @mbg.generated
     */
    private String fomulaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.phar_check_mark
     *
     * @mbg.generated
     */
    private String pharCheckMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.phar_check_time
     *
     * @mbg.generated
     */
    private String pharCheckTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_morder.charge_code
     *
     * @mbg.generated
     */
    private String chargeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_id
     *
     * @return the value of zmap_c_m2_morder.morder_id
     *
     * @mbg.generated
     */
    public String getMorderId() {
        return morderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_id
     *
     * @param morderId the value for zmap_c_m2_morder.morder_id
     *
     * @mbg.generated
     */
    public void setMorderId(String morderId) {
        this.morderId = morderId == null ? null : morderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_code
     *
     * @return the value of zmap_c_m2_morder.morder_code
     *
     * @mbg.generated
     */
    public String getMorderCode() {
        return morderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_code
     *
     * @param morderCode the value for zmap_c_m2_morder.morder_code
     *
     * @mbg.generated
     */
    public void setMorderCode(String morderCode) {
        this.morderCode = morderCode == null ? null : morderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.related_code
     *
     * @return the value of zmap_c_m2_morder.related_code
     *
     * @mbg.generated
     */
    public String getRelatedCode() {
        return relatedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.related_code
     *
     * @param relatedCode the value for zmap_c_m2_morder.related_code
     *
     * @mbg.generated
     */
    public void setRelatedCode(String relatedCode) {
        this.relatedCode = relatedCode == null ? null : relatedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.patient_code
     *
     * @return the value of zmap_c_m2_morder.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.patient_code
     *
     * @param patientCode the value for zmap_c_m2_morder.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.patient_name
     *
     * @return the value of zmap_c_m2_morder.patient_name
     *
     * @mbg.generated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.patient_name
     *
     * @param patientName the value for zmap_c_m2_morder.patient_name
     *
     * @mbg.generated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.mhome_page_code
     *
     * @return the value of zmap_c_m2_morder.mhome_page_code
     *
     * @mbg.generated
     */
    public String getMhomePageCode() {
        return mhomePageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.mhome_page_code
     *
     * @param mhomePageCode the value for zmap_c_m2_morder.mhome_page_code
     *
     * @mbg.generated
     */
    public void setMhomePageCode(String mhomePageCode) {
        this.mhomePageCode = mhomePageCode == null ? null : mhomePageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.reg_seq
     *
     * @return the value of zmap_c_m2_morder.reg_code
     *
     * @mbg.generated
     */
    public String getRegSeq() {
        return regSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.reg_seq
     *
     * @param regSeq the value for zmap_c_m2_morder.reg_code
     *
     * @mbg.generated
     */
    public void setRegSeq(String regSeq) {
        this.regSeq = regSeq == null ? null : regSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.dept_code
     *
     * @return the value of zmap_c_m2_morder.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.dept_code
     *
     * @param deptCode the value for zmap_c_m2_morder.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_status
     *
     * @return the value of zmap_c_m2_morder.morder_status
     *
     * @mbg.generated
     */
    public String getMorderStatus() {
        return morderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_status
     *
     * @param morderStatus the value for zmap_c_m2_morder.morder_status
     *
     * @mbg.generated
     */
    public void setMorderStatus(String morderStatus) {
        this.morderStatus = morderStatus == null ? null : morderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.is_valid
     *
     * @return the value of zmap_c_m2_morder.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.is_valid
     *
     * @param isValid the value for zmap_c_m2_morder.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.treat_type_code
     *
     * @return the value of zmap_c_m2_morder.treat_type_code
     *
     * @mbg.generated
     */
    public String getTreatTypeCode() {
        return treatTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.treat_type_code
     *
     * @param treatTypeCode the value for zmap_c_m2_morder.treat_type_code
     *
     * @mbg.generated
     */
    public void setTreatTypeCode(String treatTypeCode) {
        this.treatTypeCode = treatTypeCode == null ? null : treatTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.treat_code
     *
     * @return the value of zmap_c_m2_morder.treat_code
     *
     * @mbg.generated
     */
    public String getTreatCode() {
        return treatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.treat_code
     *
     * @param treatCode the value for zmap_c_m2_morder.treat_code
     *
     * @mbg.generated
     */
    public void setTreatCode(String treatCode) {
        this.treatCode = treatCode == null ? null : treatCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.treat_body_part
     *
     * @return the value of zmap_c_m2_morder.treat_body_part
     *
     * @mbg.generated
     */
    public String getTreatBodyPart() {
        return treatBodyPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.treat_body_part
     *
     * @param treatBodyPart the value for zmap_c_m2_morder.treat_body_part
     *
     * @mbg.generated
     */
    public void setTreatBodyPart(String treatBodyPart) {
        this.treatBodyPart = treatBodyPart == null ? null : treatBodyPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.fee_item_code
     *
     * @return the value of zmap_c_m2_morder.fee_item_code
     *
     * @mbg.generated
     */
    public String getFeeItemCode() {
        return feeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.fee_item_code
     *
     * @param feeItemCode the value for zmap_c_m2_morder.fee_item_code
     *
     * @mbg.generated
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode == null ? null : feeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.days
     *
     * @return the value of zmap_c_m2_morder.days
     *
     * @mbg.generated
     */
    public String getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.days
     *
     * @param days the value for zmap_c_m2_morder.days
     *
     * @mbg.generated
     */
    public void setDays(String days) {
        this.days = days == null ? null : days.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.single_use_volumn
     *
     * @return the value of zmap_c_m2_morder.single_use_volumn
     *
     * @mbg.generated
     */
    public String getSingleUseVolumn() {
        return singleUseVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.single_use_volumn
     *
     * @param singleUseVolumn the value for zmap_c_m2_morder.single_use_volumn
     *
     * @mbg.generated
     */
    public void setSingleUseVolumn(String singleUseVolumn) {
        this.singleUseVolumn = singleUseVolumn == null ? null : singleUseVolumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.total_use_volumn
     *
     * @return the value of zmap_c_m2_morder.total_use_volumn
     *
     * @mbg.generated
     */
    public String getTotalUseVolumn() {
        return totalUseVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.total_use_volumn
     *
     * @param totalUseVolumn the value for zmap_c_m2_morder.total_use_volumn
     *
     * @mbg.generated
     */
    public void setTotalUseVolumn(String totalUseVolumn) {
        this.totalUseVolumn = totalUseVolumn == null ? null : totalUseVolumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_content
     *
     * @return the value of zmap_c_m2_morder.morder_content
     *
     * @mbg.generated
     */
    public String getMorderContent() {
        return morderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_content
     *
     * @param morderContent the value for zmap_c_m2_morder.morder_content
     *
     * @mbg.generated
     */
    public void setMorderContent(String morderContent) {
        this.morderContent = morderContent == null ? null : morderContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_special
     *
     * @return the value of zmap_c_m2_morder.morder_special
     *
     * @mbg.generated
     */
    public String getMorderSpecial() {
        return morderSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_special
     *
     * @param morderSpecial the value for zmap_c_m2_morder.morder_special
     *
     * @mbg.generated
     */
    public void setMorderSpecial(String morderSpecial) {
        this.morderSpecial = morderSpecial == null ? null : morderSpecial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.skin_test_result
     *
     * @return the value of zmap_c_m2_morder.skin_test_result
     *
     * @mbg.generated
     */
    public String getSkinTestResult() {
        return skinTestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.skin_test_result
     *
     * @param skinTestResult the value for zmap_c_m2_morder.skin_test_result
     *
     * @mbg.generated
     */
    public void setSkinTestResult(String skinTestResult) {
        this.skinTestResult = skinTestResult == null ? null : skinTestResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_dept_code
     *
     * @return the value of zmap_c_m2_morder.exec_dept_code
     *
     * @mbg.generated
     */
    public String getExecDeptCode() {
        return execDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_dept_code
     *
     * @param execDeptCode the value for zmap_c_m2_morder.exec_dept_code
     *
     * @mbg.generated
     */
    public void setExecDeptCode(String execDeptCode) {
        this.execDeptCode = execDeptCode == null ? null : execDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_freq
     *
     * @return the value of zmap_c_m2_morder.exec_freq
     *
     * @mbg.generated
     */
    public String getExecFreq() {
        return execFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_freq
     *
     * @param execFreq the value for zmap_c_m2_morder.exec_freq
     *
     * @mbg.generated
     */
    public void setExecFreq(String execFreq) {
        this.execFreq = execFreq == null ? null : execFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.freq_times
     *
     * @return the value of zmap_c_m2_morder.freq_times
     *
     * @mbg.generated
     */
    public String getFreqTimes() {
        return freqTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.freq_times
     *
     * @param freqTimes the value for zmap_c_m2_morder.freq_times
     *
     * @mbg.generated
     */
    public void setFreqTimes(String freqTimes) {
        this.freqTimes = freqTimes == null ? null : freqTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.freq_interval
     *
     * @return the value of zmap_c_m2_morder.freq_interval
     *
     * @mbg.generated
     */
    public String getFreqInterval() {
        return freqInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.freq_interval
     *
     * @param freqInterval the value for zmap_c_m2_morder.freq_interval
     *
     * @mbg.generated
     */
    public void setFreqInterval(String freqInterval) {
        this.freqInterval = freqInterval == null ? null : freqInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.interval_time_unit
     *
     * @return the value of zmap_c_m2_morder.interval_time_unit
     *
     * @mbg.generated
     */
    public String getIntervalTimeUnit() {
        return intervalTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.interval_time_unit
     *
     * @param intervalTimeUnit the value for zmap_c_m2_morder.interval_time_unit
     *
     * @mbg.generated
     */
    public void setIntervalTimeUnit(String intervalTimeUnit) {
        this.intervalTimeUnit = intervalTimeUnit == null ? null : intervalTimeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_schedule
     *
     * @return the value of zmap_c_m2_morder.exec_schedule
     *
     * @mbg.generated
     */
    public String getExecSchedule() {
        return execSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_schedule
     *
     * @param execSchedule the value for zmap_c_m2_morder.exec_schedule
     *
     * @mbg.generated
     */
    public void setExecSchedule(String execSchedule) {
        this.execSchedule = execSchedule == null ? null : execSchedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_type_code
     *
     * @return the value of zmap_c_m2_morder.exec_type_code
     *
     * @mbg.generated
     */
    public String getExecTypeCode() {
        return execTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_type_code
     *
     * @param execTypeCode the value for zmap_c_m2_morder.exec_type_code
     *
     * @mbg.generated
     */
    public void setExecTypeCode(String execTypeCode) {
        this.execTypeCode = execTypeCode == null ? null : execTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_mark
     *
     * @return the value of zmap_c_m2_morder.exec_mark
     *
     * @mbg.generated
     */
    public String getExecMark() {
        return execMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_mark
     *
     * @param execMark the value for zmap_c_m2_morder.exec_mark
     *
     * @mbg.generated
     */
    public void setExecMark(String execMark) {
        this.execMark = execMark == null ? null : execMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_begin_time
     *
     * @return the value of zmap_c_m2_morder.exec_begin_time
     *
     * @mbg.generated
     */
    public String getExecBeginTime() {
        return execBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_begin_time
     *
     * @param execBeginTime the value for zmap_c_m2_morder.exec_begin_time
     *
     * @mbg.generated
     */
    public void setExecBeginTime(String execBeginTime) {
        this.execBeginTime = execBeginTime == null ? null : execBeginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.exec_end_time
     *
     * @return the value of zmap_c_m2_morder.exec_end_time
     *
     * @mbg.generated
     */
    public String getExecEndTime() {
        return execEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.exec_end_time
     *
     * @param execEndTime the value for zmap_c_m2_morder.exec_end_time
     *
     * @mbg.generated
     */
    public void setExecEndTime(String execEndTime) {
        this.execEndTime = execEndTime == null ? null : execEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.last_exec_time
     *
     * @return the value of zmap_c_m2_morder.last_exec_time
     *
     * @mbg.generated
     */
    public String getLastExecTime() {
        return lastExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.last_exec_time
     *
     * @param lastExecTime the value for zmap_c_m2_morder.last_exec_time
     *
     * @mbg.generated
     */
    public void setLastExecTime(String lastExecTime) {
        this.lastExecTime = lastExecTime == null ? null : lastExecTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_dept_code
     *
     * @return the value of zmap_c_m2_morder.morder_dept_code
     *
     * @mbg.generated
     */
    public String getMorderDeptCode() {
        return morderDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_dept_code
     *
     * @param morderDeptCode the value for zmap_c_m2_morder.morder_dept_code
     *
     * @mbg.generated
     */
    public void setMorderDeptCode(String morderDeptCode) {
        this.morderDeptCode = morderDeptCode == null ? null : morderDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_doctor_code
     *
     * @return the value of zmap_c_m2_morder.morder_doctor_code
     *
     * @mbg.generated
     */
    public String getMorderDoctorCode() {
        return morderDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_doctor_code
     *
     * @param morderDoctorCode the value for zmap_c_m2_morder.morder_doctor_code
     *
     * @mbg.generated
     */
    public void setMorderDoctorCode(String morderDoctorCode) {
        this.morderDoctorCode = morderDoctorCode == null ? null : morderDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.morder_time
     *
     * @return the value of zmap_c_m2_morder.morder_time
     *
     * @mbg.generated
     */
    public String getMorderTime() {
        return morderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.morder_time
     *
     * @param morderTime the value for zmap_c_m2_morder.morder_time
     *
     * @mbg.generated
     */
    public void setMorderTime(String morderTime) {
        this.morderTime = morderTime == null ? null : morderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.proofread_nurse
     *
     * @return the value of zmap_c_m2_morder.proofread_nurse
     *
     * @mbg.generated
     */
    public String getProofreadNurse() {
        return proofreadNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.proofread_nurse
     *
     * @param proofreadNurse the value for zmap_c_m2_morder.proofread_nurse
     *
     * @mbg.generated
     */
    public void setProofreadNurse(String proofreadNurse) {
        this.proofreadNurse = proofreadNurse == null ? null : proofreadNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.proofread_time
     *
     * @return the value of zmap_c_m2_morder.proofread_time
     *
     * @mbg.generated
     */
    public String getProofreadTime() {
        return proofreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.proofread_time
     *
     * @param proofreadTime the value for zmap_c_m2_morder.proofread_time
     *
     * @mbg.generated
     */
    public void setProofreadTime(String proofreadTime) {
        this.proofreadTime = proofreadTime == null ? null : proofreadTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.stop_doctor_code
     *
     * @return the value of zmap_c_m2_morder.stop_doctor_code
     *
     * @mbg.generated
     */
    public String getStopDoctorCode() {
        return stopDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.stop_doctor_code
     *
     * @param stopDoctorCode the value for zmap_c_m2_morder.stop_doctor_code
     *
     * @mbg.generated
     */
    public void setStopDoctorCode(String stopDoctorCode) {
        this.stopDoctorCode = stopDoctorCode == null ? null : stopDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.stop_time
     *
     * @return the value of zmap_c_m2_morder.stop_time
     *
     * @mbg.generated
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.stop_time
     *
     * @param stopTime the value for zmap_c_m2_morder.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(String stopTime) {
        this.stopTime = stopTime == null ? null : stopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.confirmed_stop_time
     *
     * @return the value of zmap_c_m2_morder.confirmed_stop_time
     *
     * @mbg.generated
     */
    public String getConfirmedStopTime() {
        return confirmedStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.confirmed_stop_time
     *
     * @param confirmedStopTime the value for zmap_c_m2_morder.confirmed_stop_time
     *
     * @mbg.generated
     */
    public void setConfirmedStopTime(String confirmedStopTime) {
        this.confirmedStopTime = confirmedStopTime == null ? null : confirmedStopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.confirmed_stop_nurse
     *
     * @return the value of zmap_c_m2_morder.confirmed_stop_nurse
     *
     * @mbg.generated
     */
    public String getConfirmedStopNurse() {
        return confirmedStopNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.confirmed_stop_nurse
     *
     * @param confirmedStopNurse the value for zmap_c_m2_morder.confirmed_stop_nurse
     *
     * @mbg.generated
     */
    public void setConfirmedStopNurse(String confirmedStopNurse) {
        this.confirmedStopNurse = confirmedStopNurse == null ? null : confirmedStopNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.check_mark
     *
     * @return the value of zmap_c_m2_morder.check_mark
     *
     * @mbg.generated
     */
    public String getCheckMark() {
        return checkMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.check_mark
     *
     * @param checkMark the value for zmap_c_m2_morder.check_mark
     *
     * @mbg.generated
     */
    public void setCheckMark(String checkMark) {
        this.checkMark = checkMark == null ? null : checkMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.check_status
     *
     * @return the value of zmap_c_m2_morder.check_status
     *
     * @mbg.generated
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.check_status
     *
     * @param checkStatus the value for zmap_c_m2_morder.check_status
     *
     * @mbg.generated
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus == null ? null : checkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.first_use_volumn
     *
     * @return the value of zmap_c_m2_morder.first_use_volumn
     *
     * @mbg.generated
     */
    public String getFirstUseVolumn() {
        return firstUseVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.first_use_volumn
     *
     * @param firstUseVolumn the value for zmap_c_m2_morder.first_use_volumn
     *
     * @mbg.generated
     */
    public void setFirstUseVolumn(String firstUseVolumn) {
        this.firstUseVolumn = firstUseVolumn == null ? null : firstUseVolumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.over_use_volumn
     *
     * @return the value of zmap_c_m2_morder.over_use_volumn
     *
     * @mbg.generated
     */
    public String getOverUseVolumn() {
        return overUseVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.over_use_volumn
     *
     * @param overUseVolumn the value for zmap_c_m2_morder.over_use_volumn
     *
     * @mbg.generated
     */
    public void setOverUseVolumn(String overUseVolumn) {
        this.overUseVolumn = overUseVolumn == null ? null : overUseVolumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.combined_item_code
     *
     * @return the value of zmap_c_m2_morder.combined_item_code
     *
     * @mbg.generated
     */
    public String getCombinedItemCode() {
        return combinedItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.combined_item_code
     *
     * @param combinedItemCode the value for zmap_c_m2_morder.combined_item_code
     *
     * @mbg.generated
     */
    public void setCombinedItemCode(String combinedItemCode) {
        this.combinedItemCode = combinedItemCode == null ? null : combinedItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.fomula_code
     *
     * @return the value of zmap_c_m2_morder.fomula_code
     *
     * @mbg.generated
     */
    public String getFomulaCode() {
        return fomulaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.fomula_code
     *
     * @param fomulaCode the value for zmap_c_m2_morder.fomula_code
     *
     * @mbg.generated
     */
    public void setFomulaCode(String fomulaCode) {
        this.fomulaCode = fomulaCode == null ? null : fomulaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.phar_check_mark
     *
     * @return the value of zmap_c_m2_morder.phar_check_mark
     *
     * @mbg.generated
     */
    public String getPharCheckMark() {
        return pharCheckMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.phar_check_mark
     *
     * @param pharCheckMark the value for zmap_c_m2_morder.phar_check_mark
     *
     * @mbg.generated
     */
    public void setPharCheckMark(String pharCheckMark) {
        this.pharCheckMark = pharCheckMark == null ? null : pharCheckMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.phar_check_time
     *
     * @return the value of zmap_c_m2_morder.phar_check_time
     *
     * @mbg.generated
     */
    public String getPharCheckTime() {
        return pharCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.phar_check_time
     *
     * @param pharCheckTime the value for zmap_c_m2_morder.phar_check_time
     *
     * @mbg.generated
     */
    public void setPharCheckTime(String pharCheckTime) {
        this.pharCheckTime = pharCheckTime == null ? null : pharCheckTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_morder.charge_code
     *
     * @return the value of zmap_c_m2_morder.charge_code
     *
     * @mbg.generated
     */
    public String getChargeCode() {
        return chargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_morder.charge_code
     *
     * @param chargeCode the value for zmap_c_m2_morder.charge_code
     *
     * @mbg.generated
     */
    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode == null ? null : chargeCode.trim();
    }
}