package com.zmap.zmap.clinic.model;

public class ZmapClinicCM2DrugUseSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    private String drugUseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.clinic_id
     *
     * @mbg.generated
     */
    private String clinicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    private String drugUseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    private String drugUseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    private String drugTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    private String drugCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    private String drugDose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    private String useFreq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_drug_use.iccard_code
     *
     * @mbg.generated
     */
    private String iccardCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_use_id
     *
     * @return the value of zmap_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    
    private String zmapDeptCode;
    private String zmapDrugCode;
    private String hospitalCode;
    private String subHospitalCode;
    
    
    
    
    public String getZmapDeptCode() {
		return zmapDeptCode;
	}

	public void setZmapDeptCode(String zmapDeptCode) {
		this.zmapDeptCode = zmapDeptCode== null ? null : zmapDeptCode.trim();
	}

	public String getZmapDrugCode() {
		return zmapDrugCode;
	}

	public void setZmapDrugCode(String zmapDrugCode) {
		this.zmapDrugCode = zmapDrugCode== null ? null : zmapDrugCode.trim();
	}

	public String getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode== null ? null : hospitalCode.trim();
	}

	public String getSubHospitalCode() {
		return subHospitalCode;
	}

	public void setSubHospitalCode(String subHospitalCode) {
		this.subHospitalCode = subHospitalCode== null ? null : subHospitalCode.trim();
	}

	public String getDrugUseId() {
        return drugUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_use_id
     *
     * @param drugUseId the value for zmap_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    public void setDrugUseId(String drugUseId) {
        this.drugUseId = drugUseId == null ? null : drugUseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.clinic_id
     *
     * @return the value of zmap_m2_drug_use.clinic_id
     *
     * @mbg.generated
     */
    public String getClinicCode() {
        return clinicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.clinic_id
     *
     * @param clinicCode the value for zmap_m2_drug_use.clinic_id
     *
     * @mbg.generated
     */
    public void setClinicCode(String clinicCode) {
        this.clinicCode = clinicCode == null ? null : clinicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_use_code
     *
     * @return the value of zmap_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    public String getDrugUseCode() {
        return drugUseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_use_code
     *
     * @param drugUseCode the value for zmap_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    public void setDrugUseCode(String drugUseCode) {
        this.drugUseCode = drugUseCode == null ? null : drugUseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_use_time
     *
     * @return the value of zmap_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    public String getDrugUseTime() {
        return drugUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_use_time
     *
     * @param drugUseTime the value for zmap_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    public void setDrugUseTime(String drugUseTime) {
        this.drugUseTime = drugUseTime == null ? null : drugUseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.reg_code
     *
     * @return the value of zmap_m2_drug_use.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.reg_code
     *
     * @param regCode the value for zmap_m2_drug_use.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.patient_code
     *
     * @return the value of zmap_m2_drug_use.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.patient_code
     *
     * @param patientCode the value for zmap_m2_drug_use.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.doctor_code
     *
     * @return the value of zmap_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.doctor_code
     *
     * @param doctorCode the value for zmap_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.dept_code
     *
     * @return the value of zmap_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.dept_code
     *
     * @param deptCode the value for zmap_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_type_code
     *
     * @return the value of zmap_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    public String getDrugTypeCode() {
        return drugTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_type_code
     *
     * @param drugTypeCode the value for zmap_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    public void setDrugTypeCode(String drugTypeCode) {
        this.drugTypeCode = drugTypeCode == null ? null : drugTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_code
     *
     * @return the value of zmap_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_code
     *
     * @param drugCode the value for zmap_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode == null ? null : drugCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.drug_dose
     *
     * @return the value of zmap_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    public String getDrugDose() {
        return drugDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.drug_dose
     *
     * @param drugDose the value for zmap_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    public void setDrugDose(String drugDose) {
        this.drugDose = drugDose == null ? null : drugDose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.use_freq
     *
     * @return the value of zmap_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    public String getUseFreq() {
        return useFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.use_freq
     *
     * @param useFreq the value for zmap_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    public void setUseFreq(String useFreq) {
        this.useFreq = useFreq == null ? null : useFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_drug_use.iccard_code
     *
     * @return the value of zmap_m2_drug_use.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_drug_use.iccard_code
     *
     * @param iccardCode the value for zmap_m2_drug_use.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }
}