package com.zmap.zmap.clinic.model;

public class ZmapClinicCM1SyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m1_clinics.clinic_id
     *
     * @mbg.generated
     */
    private String clinicId;
    private String regCode;
    private String regTime;
    private String patientCode;
    private String doctorCode;
    private String deptCode;
    private String orgCode;
    private String iccardCode;
    
    private String zmapDeptCode;
    private String clinicType;
    private String hospitalCode;
    private String subHospitalCode;
    private String isTrans;
	private String transRegType;
	private String transDeptCode;
	private String transDoctorCode;
	private String transStatus;
	private int clinicNum;
	private int deptCount;
	private int doctorCount;
    
    
    public String getIsTrans() {
		return isTrans;
	}

	public void setIsTrans(String isTrans) {
		this.isTrans = isTrans;
	}

	public String getTransRegType() {
		return transRegType;
	}

	public void setTransRegType(String transRegType) {
		this.transRegType = transRegType;
	}

	public String getTransDeptCode() {
		return transDeptCode;
	}

	public void setTransDeptCode(String transDeptCode) {
		this.transDeptCode = transDeptCode;
	}

	public String getTransDoctorCode() {
		return transDoctorCode;
	}

	public void setTransDoctorCode(String transDoctorCode) {
		this.transDoctorCode = transDoctorCode;
	}

	public String getTransStatus() {
		return transStatus;
	}

	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus;
	}

	public String getZmapDeptCode() {
		return zmapDeptCode;
	}

	public void setZmapDeptCode(String zmapDeptCode) {
		this.zmapDeptCode = zmapDeptCode== null ? null : zmapDeptCode.trim();
	}

	public String getClinicType() {
		return clinicType;
	}

	public void setClinicType(String clinicType) {
		this.clinicType = clinicType== null ? null : clinicType.trim();
	}

	public String getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode== null ? null : hospitalCode.trim();
	}

	public String getSubHospitalCode() {
		return subHospitalCode;
	}

	public void setSubHospitalCode(String subHospitalCode) {
		this.subHospitalCode = subHospitalCode== null ? null : subHospitalCode.trim();
	}

	public String getClinicId() {
        return clinicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.clinic_id
     *
     * @param clinicId the value for zmap_m1_clinics.clinic_id
     *
     * @mbg.generated
     */
    public void setClinicId(String clinicId) {
        this.clinicId = clinicId == null ? null : clinicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.reg_code
     *
     * @return the value of zmap_m1_clinics.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.reg_code
     *
     * @param regCode the value for zmap_m1_clinics.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.reg_time
     *
     * @return the value of zmap_m1_clinics.reg_time
     *
     * @mbg.generated
     */
    public String getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.reg_time
     *
     * @param regTime the value for zmap_m1_clinics.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime == null ? null : regTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.patient_code
     *
     * @return the value of zmap_m1_clinics.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.patient_code
     *
     * @param patientCode the value for zmap_m1_clinics.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.doctor_code
     *
     * @return the value of zmap_m1_clinics.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.doctor_code
     *
     * @param doctorCode the value for zmap_m1_clinics.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.dept_code
     *
     * @return the value of zmap_m1_clinics.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.dept_code
     *
     * @param deptCode the value for zmap_m1_clinics.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.org_code
     *
     * @return the value of zmap_m1_clinics.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.org_code
     *
     * @param orgCode the value for zmap_m1_clinics.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m1_clinics.iccard_code
     *
     * @return the value of zmap_m1_clinics.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m1_clinics.iccard_code
     *
     * @param iccardCode the value for zmap_m1_clinics.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }

	public int getClinicNum() {
		return clinicNum;
	}

	public void setClinicNum(int clinicNum) {
		this.clinicNum = clinicNum;
	}

	public int getDeptCount() {
		return deptCount;
	}

	public void setDeptCount(int deptCount) {
		this.deptCount = deptCount;
	}

	public int getDoctorCount() {
		return doctorCount;
	}

	public void setDoctorCount(int doctorCount) {
		this.doctorCount = doctorCount;
	}


}