package com.zmap.zmap.clinic.model;

import java.math.BigDecimal;

public class ZmapClinicCM2ChargeSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.charge_id
     *
     * @mbg.generated
     */
    private String chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.clinic_id
     *
     * @mbg.generated
     */
    private String clinicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.charge_code
     *
     * @mbg.generated
     */
    private String chargeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.charge_time
     *
     * @mbg.generated
     */
    private String chargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    private String feeClassCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    private String feeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    private String feeSourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.settle_type_code
     *
     * @mbg.generated
     */
    private String settleTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.num
     *
     * @mbg.generated
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.price
     *
     * @mbg.generated
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.discount_amount
     *
     * @mbg.generated
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.discount_rate
     *
     * @mbg.generated
     */
    private String discountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_m2_charge.iccard_code
     *
     * @mbg.generated
     */
    private String iccardCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.charge_id
     *
     * @return the value of zmap_m2_charge.charge_id
     *
     * @mbg.generated
     */
    
    private String zmapDeptCode;
    private String zmapFeeItemCode;
    private String subHospitalCode;
    private String hospitalCode;
    private String feeTypeCode;
    private String isInsuresettle;
    private String acctItemCode;
    private String settleAcctCode;
    private String recStatus;
	private String recType;
	private String morderCode;
    
    
    
	public String getMorderCode() {
		return morderCode;
	}

	public void setMorderCode(String morderCode) {
		this.morderCode = morderCode;
	}

	public String getRecStatus() {
		return recStatus;
	}

	public void setRecStatus(String recStatus) {
		this.recStatus = recStatus;
	}

	public String getRecType() {
		return recType;
	}

	public void setRecType(String recType) {
		this.recType = recType;
	}

	public String getSettleAcctCode() {
		return settleAcctCode;
	}

	public void setSettleAcctCode(String settleAcctCode) {
		this.settleAcctCode = settleAcctCode;
	}

	public String getAcctItemCode() {
		return acctItemCode;
	}

	public void setAcctItemCode(String acctItemCode) {
		this.acctItemCode = acctItemCode;
	}

	public String getIsInsuresettle() {
		return isInsuresettle;
	}

	public void setIsInsuresettle(String isInsuresettle) {
		this.isInsuresettle = isInsuresettle;
	}

	public String getFeeTypeCode() {
		return feeTypeCode;
	}

	public void setFeeTypeCode(String feeTypeCode) {
		this.feeTypeCode = feeTypeCode;
	}


	public String getZmapDeptCode() {
		return zmapDeptCode;
	}

	public void setZmapDeptCode(String zmapDeptCode) {
		this.zmapDeptCode = zmapDeptCode== null ? null :zmapDeptCode.trim();
	}

	public String getZmapFeeItemCode() {
		return zmapFeeItemCode;
	}

	public void setZmapFeeItemCode(String zmapFeeItemCode) {
		this.zmapFeeItemCode = zmapFeeItemCode== null ? null : zmapFeeItemCode.trim();
	}

	public String getSubHospitalCode() {
		return subHospitalCode;
	}

	public void setSubHospitalCode(String subHospitalCode) {
		this.subHospitalCode = subHospitalCode== null ? null : subHospitalCode.trim();
	}

	public String getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode== null ? null : hospitalCode.trim();
	}

	public String getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.charge_id
     *
     * @param chargeId the value for zmap_m2_charge.charge_id
     *
     * @mbg.generated
     */
    public void setChargeId(String chargeId) {
        this.chargeId = chargeId == null ? null : chargeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.clinic_id
     *
     * @return the value of zmap_m2_charge.clinic_id
     *
     * @mbg.generated
     */
    public String getClinicCode() {
        return clinicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.clinic_id
     *
     * @param clinicId the value for zmap_m2_charge.clinic_id
     *
     * @mbg.generated
     */
    public void setClinicCode(String clinicCode) {
        this.clinicCode = clinicCode == null ? null : clinicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.charge_code
     *
     * @return the value of zmap_m2_charge.charge_code
     *
     * @mbg.generated
     */
    public String getChargeCode() {
        return chargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.charge_code
     *
     * @param chargeCode the value for zmap_m2_charge.charge_code
     *
     * @mbg.generated
     */
    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode == null ? null : chargeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.reg_code
     *
     * @return the value of zmap_m2_charge.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.reg_code
     *
     * @param regCode the value for zmap_m2_charge.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.patient_code
     *
     * @return the value of zmap_m2_charge.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.patient_code
     *
     * @param patientCode the value for zmap_m2_charge.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.charge_time
     *
     * @return the value of zmap_m2_charge.charge_time
     *
     * @mbg.generated
     */
    public String getChargeTime() {
        return chargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.charge_time
     *
     * @param chargeTime the value for zmap_m2_charge.charge_time
     *
     * @mbg.generated
     */
    public void setChargeTime(String chargeTime) {
        this.chargeTime = chargeTime == null ? null : chargeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.dept_code
     *
     * @return the value of zmap_m2_charge.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.dept_code
     *
     * @param deptCode the value for zmap_m2_charge.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.doctor_code
     *
     * @return the value of zmap_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.doctor_code
     *
     * @param doctorCode the value for zmap_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.fee_class_code
     *
     * @return the value of zmap_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    public String getFeeClassCode() {
        return feeClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.fee_class_code
     *
     * @param feeClassCode the value for zmap_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    public void setFeeClassCode(String feeClassCode) {
        this.feeClassCode = feeClassCode == null ? null : feeClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.fee_item_code
     *
     * @return the value of zmap_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    public String getFeeItemCode() {
        return feeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.fee_item_code
     *
     * @param feeItemCode the value for zmap_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode == null ? null : feeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.fee_source_code
     *
     * @return the value of zmap_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    public String getFeeSourceCode() {
        return feeSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.fee_source_code
     *
     * @param feeSourceCode the value for zmap_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    public void setFeeSourceCode(String feeSourceCode) {
        this.feeSourceCode = feeSourceCode == null ? null : feeSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.settle_type_code
     *
     * @return the value of zmap_m2_charge.settle_type_code
     *
     * @mbg.generated
     */
    public String getSettleTypeCode() {
        return settleTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.settle_type_code
     *
     * @param settleTypeCode the value for zmap_m2_charge.settle_type_code
     *
     * @mbg.generated
     */
    public void setSettleTypeCode(String settleTypeCode) {
        this.settleTypeCode = settleTypeCode == null ? null : settleTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.amount
     *
     * @return the value of zmap_m2_charge.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.amount
     *
     * @param amount the value for zmap_m2_charge.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.num
     *
     * @return the value of zmap_m2_charge.num
     *
     * @mbg.generated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.num
     *
     * @param num the value for zmap_m2_charge.num
     *
     * @mbg.generated
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.price
     *
     * @return the value of zmap_m2_charge.price
     *
     * @mbg.generated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.price
     *
     * @paramunitPrice the value for zmap_m2_charge.price
     *
     * @mbg.generated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice =unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.size
     *
     * @return the value of zmap_m2_charge.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.size
     *
     * @param size the value for zmap_m2_charge.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.discount_amount
     *
     * @return the value of zmap_m2_charge.discount_amount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.discount_amount
     *
     * @param discountAmount the value for zmap_m2_charge.discount_amount
     *
     * @mbg.generated
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.discount_rate
     *
     * @return the value of zmap_m2_charge.discount_rate
     *
     * @mbg.generated
     */
    public String getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.discount_rate
     *
     * @param discountRate the value for zmap_m2_charge.discount_rate
     *
     * @mbg.generated
     */
    public void setDiscountRate(String discountRate) {
        this.discountRate = discountRate == null ? null : discountRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_m2_charge.iccard_code
     *
     * @return the value of zmap_m2_charge.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_m2_charge.iccard_code
     *
     * @param iccardCode the value for zmap_m2_charge.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }
}