package com.zmap.zmap.clinic.model;

public class ZmapClinicCM2DiagnoseSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.diag_id
     *
     * @mbg.generated
     */
    private String diagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.clinic_code
     *
     * @mbg.generated
     */
    private String clinicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.diag_flow_code
     *
     * @mbg.generated
     */
    private String diagFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.diag_time
     *
     * @mbg.generated
     */
    private String diagTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.patient_code
     *
     * @mbg.generated
     */
    private String patientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.zmap_dept_code
     *
     * @mbg.generated
     */
    private String zmapDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.diag_code
     *
     * @mbg.generated
     */
    private String diagCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.zmap_diag_code
     *
     * @mbg.generated
     */
    private String zmapDiagCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.diag_result
     *
     * @mbg.generated
     */
    private String diagResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.iccard_code
     *
     * @mbg.generated
     */
    private String iccardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_c_m2_diagnose.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.diag_id
     *
     * @return the value of zmap_c_m2_diagnose.diag_id
     *
     * @mbg.generated
     */
    public String getDiagId() {
        return diagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.diag_id
     *
     * @param diagId the value for zmap_c_m2_diagnose.diag_id
     *
     * @mbg.generated
     */
    public void setDiagId(String diagId) {
        this.diagId = diagId == null ? null : diagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.clinic_code
     *
     * @return the value of zmap_c_m2_diagnose.clinic_code
     *
     * @mbg.generated
     */
    public String getClinicCode() {
        return clinicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.clinic_code
     *
     * @param clinicCode the value for zmap_c_m2_diagnose.clinic_code
     *
     * @mbg.generated
     */
    public void setClinicCode(String clinicCode) {
        this.clinicCode = clinicCode == null ? null : clinicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.diag_flow_code
     *
     * @return the value of zmap_c_m2_diagnose.diag_flow_code
     *
     * @mbg.generated
     */
    public String getDiagFlowCode() {
        return diagFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.diag_flow_code
     *
     * @param diagFlowCode the value for zmap_c_m2_diagnose.diag_flow_code
     *
     * @mbg.generated
     */
    public void setDiagFlowCode(String diagFlowCode) {
        this.diagFlowCode = diagFlowCode == null ? null : diagFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.diag_time
     *
     * @return the value of zmap_c_m2_diagnose.diag_time
     *
     * @mbg.generated
     */
    public String getDiagTime() {
        return diagTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.diag_time
     *
     * @param diagTime the value for zmap_c_m2_diagnose.diag_time
     *
     * @mbg.generated
     */
    public void setDiagTime(String diagTime) {
        this.diagTime = diagTime == null ? null : diagTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.reg_code
     *
     * @return the value of zmap_c_m2_diagnose.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.reg_code
     *
     * @param regCode the value for zmap_c_m2_diagnose.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.patient_code
     *
     * @return the value of zmap_c_m2_diagnose.patient_code
     *
     * @mbg.generated
     */
    public String getPatientCode() {
        return patientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.patient_code
     *
     * @param patientCode the value for zmap_c_m2_diagnose.patient_code
     *
     * @mbg.generated
     */
    public void setPatientCode(String patientCode) {
        this.patientCode = patientCode == null ? null : patientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.doctor_code
     *
     * @return the value of zmap_c_m2_diagnose.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.doctor_code
     *
     * @param doctorCode the value for zmap_c_m2_diagnose.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.dept_code
     *
     * @return the value of zmap_c_m2_diagnose.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.dept_code
     *
     * @param deptCode the value for zmap_c_m2_diagnose.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.zmap_dept_code
     *
     * @return the value of zmap_c_m2_diagnose.zmap_dept_code
     *
     * @mbg.generated
     */
    public String getZmapDeptCode() {
        return zmapDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.zmap_dept_code
     *
     * @param zmapDeptCode the value for zmap_c_m2_diagnose.zmap_dept_code
     *
     * @mbg.generated
     */
    public void setZmapDeptCode(String zmapDeptCode) {
        this.zmapDeptCode = zmapDeptCode == null ? null : zmapDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.diag_code
     *
     * @return the value of zmap_c_m2_diagnose.diag_code
     *
     * @mbg.generated
     */
    public String getDiagCode() {
        return diagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.diag_code
     *
     * @param diagCode the value for zmap_c_m2_diagnose.diag_code
     *
     * @mbg.generated
     */
    public void setDiagCode(String diagCode) {
        this.diagCode = diagCode == null ? null : diagCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.zmap_diag_code
     *
     * @return the value of zmap_c_m2_diagnose.zmap_diag_code
     *
     * @mbg.generated
     */
    public String getZmapDiagCode() {
        return zmapDiagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.zmap_diag_code
     *
     * @param zmapDiagCode the value for zmap_c_m2_diagnose.zmap_diag_code
     *
     * @mbg.generated
     */
    public void setZmapDiagCode(String zmapDiagCode) {
        this.zmapDiagCode = zmapDiagCode == null ? null : zmapDiagCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.diag_result
     *
     * @return the value of zmap_c_m2_diagnose.diag_result
     *
     * @mbg.generated
     */
    public String getDiagResult() {
        return diagResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.diag_result
     *
     * @param diagResult the value for zmap_c_m2_diagnose.diag_result
     *
     * @mbg.generated
     */
    public void setDiagResult(String diagResult) {
        this.diagResult = diagResult == null ? null : diagResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.iccard_code
     *
     * @return the value of zmap_c_m2_diagnose.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.iccard_code
     *
     * @param iccardCode the value for zmap_c_m2_diagnose.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.sub_hospital_code
     *
     * @return the value of zmap_c_m2_diagnose.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_c_m2_diagnose.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_c_m2_diagnose.hospital_code
     *
     * @return the value of zmap_c_m2_diagnose.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_c_m2_diagnose.hospital_code
     *
     * @param hospitalCode the value for zmap_c_m2_diagnose.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}