package com.zmap.zmap.hospitalize.model;

public class ZmapHospitalizeHM2OperationSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.oper_flow_id
     *
     * @mbg.generated
     */
    private String operFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.in_hos_code
     *
     * @mbg.generated
     */
    private String inHosCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.oper_flow_code
     *
     * @mbg.generated
     */
    private String operFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.oper_time
     *
     * @mbg.generated
     */
    private String operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.oper_code
     *
     * @mbg.generated
     */
    private String operCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.main_doctor_code
     *
     * @mbg.generated
     */
    private String mainDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.anes_doctor_code
     *
     * @mbg.generated
     */
    private String anesDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.anes_doctor2_code
     *
     * @mbg.generated
     */
    private String anesDoctor2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.itiner_nurse_code
     *
     * @mbg.generated
     */
    private String itinerNurseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.instr_nurse_code
     *
     * @mbg.generated
     */
    private String instrNurseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.assist1_code
     *
     * @mbg.generated
     */
    private String assist1Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.assist2_code
     *
     * @mbg.generated
     */
    private String assist2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.anes_type
     *
     * @mbg.generated
     */
    private String anesType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_operation.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.oper_flow_id
     *
     * @return the value of zmap_h_m2_operation.oper_flow_id
     *
     * @mbg.generated
     */
    public String getOperFlowId() {
        return operFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.oper_flow_id
     *
     * @param operFlowId the value for zmap_h_m2_operation.oper_flow_id
     *
     * @mbg.generated
     */
    public void setOperFlowId(String operFlowId) {
        this.operFlowId = operFlowId == null ? null : operFlowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.in_hos_code
     *
     * @return the value of zmap_h_m2_operation.in_hos_code
     *
     * @mbg.generated
     */
    public String getInHosCode() {
        return inHosCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.in_hos_code
     *
     * @param inHosCode the value for zmap_h_m2_operation.in_hos_code
     *
     * @mbg.generated
     */
    public void setInHosCode(String inHosCode) {
        this.inHosCode = inHosCode == null ? null : inHosCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.oper_flow_code
     *
     * @return the value of zmap_h_m2_operation.oper_flow_code
     *
     * @mbg.generated
     */
    public String getOperFlowCode() {
        return operFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.oper_flow_code
     *
     * @param operFlowCode the value for zmap_h_m2_operation.oper_flow_code
     *
     * @mbg.generated
     */
    public void setOperFlowCode(String operFlowCode) {
        this.operFlowCode = operFlowCode == null ? null : operFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.sickman_code
     *
     * @return the value of zmap_h_m2_operation.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.sickman_code
     *
     * @param sickmanCode the value for zmap_h_m2_operation.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode == null ? null : sickmanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.oper_time
     *
     * @return the value of zmap_h_m2_operation.oper_time
     *
     * @mbg.generated
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.oper_time
     *
     * @param operTime the value for zmap_h_m2_operation.oper_time
     *
     * @mbg.generated
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.oper_code
     *
     * @return the value of zmap_h_m2_operation.oper_code
     *
     * @mbg.generated
     */
    public String getOperCode() {
        return operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.oper_code
     *
     * @param operCode the value for zmap_h_m2_operation.oper_code
     *
     * @mbg.generated
     */
    public void setOperCode(String operCode) {
        this.operCode = operCode == null ? null : operCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.main_doctor_code
     *
     * @return the value of zmap_h_m2_operation.main_doctor_code
     *
     * @mbg.generated
     */
    public String getMainDoctorCode() {
        return mainDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.main_doctor_code
     *
     * @param mainDoctorCode the value for zmap_h_m2_operation.main_doctor_code
     *
     * @mbg.generated
     */
    public void setMainDoctorCode(String mainDoctorCode) {
        this.mainDoctorCode = mainDoctorCode == null ? null : mainDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.anes_doctor_code
     *
     * @return the value of zmap_h_m2_operation.anes_doctor_code
     *
     * @mbg.generated
     */
    public String getAnesDoctorCode() {
        return anesDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.anes_doctor_code
     *
     * @param anesDoctorCode the value for zmap_h_m2_operation.anes_doctor_code
     *
     * @mbg.generated
     */
    public void setAnesDoctorCode(String anesDoctorCode) {
        this.anesDoctorCode = anesDoctorCode == null ? null : anesDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.anes_doctor2_code
     *
     * @return the value of zmap_h_m2_operation.anes_doctor2_code
     *
     * @mbg.generated
     */
    public String getAnesDoctor2Code() {
        return anesDoctor2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.anes_doctor2_code
     *
     * @param anesDoctor2Code the value for zmap_h_m2_operation.anes_doctor2_code
     *
     * @mbg.generated
     */
    public void setAnesDoctor2Code(String anesDoctor2Code) {
        this.anesDoctor2Code = anesDoctor2Code == null ? null : anesDoctor2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.itiner_nurse_code
     *
     * @return the value of zmap_h_m2_operation.itiner_nurse_code
     *
     * @mbg.generated
     */
    public String getItinerNurseCode() {
        return itinerNurseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.itiner_nurse_code
     *
     * @param itinerNurseCode the value for zmap_h_m2_operation.itiner_nurse_code
     *
     * @mbg.generated
     */
    public void setItinerNurseCode(String itinerNurseCode) {
        this.itinerNurseCode = itinerNurseCode == null ? null : itinerNurseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.instr_nurse_code
     *
     * @return the value of zmap_h_m2_operation.instr_nurse_code
     *
     * @mbg.generated
     */
    public String getInstrNurseCode() {
        return instrNurseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.instr_nurse_code
     *
     * @param instrNurseCode the value for zmap_h_m2_operation.instr_nurse_code
     *
     * @mbg.generated
     */
    public void setInstrNurseCode(String instrNurseCode) {
        this.instrNurseCode = instrNurseCode == null ? null : instrNurseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.assist1_code
     *
     * @return the value of zmap_h_m2_operation.assist1_code
     *
     * @mbg.generated
     */
    public String getAssist1Code() {
        return assist1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.assist1_code
     *
     * @param assist1Code the value for zmap_h_m2_operation.assist1_code
     *
     * @mbg.generated
     */
    public void setAssist1Code(String assist1Code) {
        this.assist1Code = assist1Code == null ? null : assist1Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.assist2_code
     *
     * @return the value of zmap_h_m2_operation.assist2_code
     *
     * @mbg.generated
     */
    public String getAssist2Code() {
        return assist2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.assist2_code
     *
     * @param assist2Code the value for zmap_h_m2_operation.assist2_code
     *
     * @mbg.generated
     */
    public void setAssist2Code(String assist2Code) {
        this.assist2Code = assist2Code == null ? null : assist2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.anes_type
     *
     * @return the value of zmap_h_m2_operation.anes_type
     *
     * @mbg.generated
     */
    public String getAnesType() {
        return anesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.anes_type
     *
     * @param anesType the value for zmap_h_m2_operation.anes_type
     *
     * @mbg.generated
     */
    public void setAnesType(String anesType) {
        this.anesType = anesType == null ? null : anesType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.sub_hospital_code
     *
     * @return the value of zmap_h_m2_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_h_m2_operation.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_operation.hospital_code
     *
     * @return the value of zmap_h_m2_operation.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_operation.hospital_code
     *
     * @param hospitalCode the value for zmap_h_m2_operation.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}