package com.zmap.zmap.hospitalize.model;

public class ZmapHospitalizeHM1HospitalizeSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.in_hos_id
     *
     * @mbg.generated
     */
    private String inHosId;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.in_hos_id
    *
    * @mbg.generated
    */
   private String inHosFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sickman_name
     *
     * @mbg.generated
     */
    private String sickmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sickman_type
     *
     * @mbg.generated
     */
    private String sickmanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.in_date
     *
     * @mbg.generated
     */
    private String inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.out_date
     *
     * @mbg.generated
     */
    private String outDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sick_area_code
     *
     * @mbg.generated
     */
    private String sickAreaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sick_bed_code
     *
     * @mbg.generated
     */
    private String sickBedCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sick_room_code
     *
     * @mbg.generated
     */
    private String sickRoomCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.resp_doctor_code
     *
     * @mbg.generated
     */
    private String respDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.rec_doctor_code
     *
     * @mbg.generated
     */
    private String recDoctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.iccard_code
     *
     * @mbg.generated
     */
    private String iccardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
     *
     * @mbg.generated
     */
    private String respDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m1_hospitalize.rec_dept_code
     *
     * @mbg.generated
     */
    private String recDeptCode;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
    *
    * @mbg.generated
    */
   private String inHosSource;
   
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
    *
    * @mbg.generated
    */
   private String inIcd;
   
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
    *
    * @mbg.generated
    */
   private String inIcdName;
   
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
    *
    * @mbg.generated
    */
   private String outIcd;
   
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column zmap_h_m1_hospitalize.resp_dept
    *
    * @mbg.generated
    */
   private String outIcdName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.in_hos_id
     *
     * @return the value of zmap_h_m1_hospitalize.in_hos_id
     *
     * @mbg.generated
     */
    public String getInHosId() {
        return inHosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.in_hos_id
     *
     * @param inHosId the value for zmap_h_m1_hospitalize.in_hos_id
     *
     * @mbg.generated
     */
    public void setInHosId(String inHosId) {
        this.inHosId = inHosId == null ? null : inHosId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sickman_code
     *
     * @return the value of zmap_h_m1_hospitalize.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sickman_code
     *
     * @param sickmanCode the value for zmap_h_m1_hospitalize.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sickman_name
     *
     * @return the value of zmap_h_m1_hospitalize.sickman_name
     *
     * @mbg.generated
     */
    public String getSickmanName() {
        return sickmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sickman_name
     *
     * @param sickmanName the value for zmap_h_m1_hospitalize.sickman_name
     *
     * @mbg.generated
     */
    public void setSickmanName(String sickmanName) {
        this.sickmanName = sickmanName == null ? null : sickmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sickman_type
     *
     * @return the value of zmap_h_m1_hospitalize.sickman_type
     *
     * @mbg.generated
     */
    public String getSickmanType() {
        return sickmanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sickman_type
     *
     * @param sickmanType the value for zmap_h_m1_hospitalize.sickman_type
     *
     * @mbg.generated
     */
    public void setSickmanType(String sickmanType) {
        this.sickmanType = sickmanType == null ? null : sickmanType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.birthday
     *
     * @return the value of zmap_h_m1_hospitalize.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.birthday
     *
     * @param birthday the value for zmap_h_m1_hospitalize.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.in_date
     *
     * @return the value of zmap_h_m1_hospitalize.in_date
     *
     * @mbg.generated
     */
    public String getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.in_date
     *
     * @param inDate the value for zmap_h_m1_hospitalize.in_date
     *
     * @mbg.generated
     */
    public void setInDate(String inDate) {
        this.inDate = inDate == null ? null : inDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.out_date
     *
     * @return the value of zmap_h_m1_hospitalize.out_date
     *
     * @mbg.generated
     */
    public String getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.out_date
     *
     * @param outDate the value for zmap_h_m1_hospitalize.out_date
     *
     * @mbg.generated
     */
    public void setOutDate(String outDate) {
        this.outDate = outDate == null ? null : outDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sick_area_code
     *
     * @return the value of zmap_h_m1_hospitalize.sick_area_code
     *
     * @mbg.generated
     */
    public String getSickAreaCode() {
        return sickAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sick_area_code
     *
     * @param sickAreaCode the value for zmap_h_m1_hospitalize.sick_area_code
     *
     * @mbg.generated
     */
    public void setSickAreaCode(String sickAreaCode) {
        this.sickAreaCode = sickAreaCode == null ? null : sickAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sick_bed_code
     *
     * @return the value of zmap_h_m1_hospitalize.sick_bed_code
     *
     * @mbg.generated
     */
    public String getSickBedCode() {
        return sickBedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sick_bed_code
     *
     * @param sickBedCode the value for zmap_h_m1_hospitalize.sick_bed_code
     *
     * @mbg.generated
     */
    public void setSickBedCode(String sickBedCode) {
        this.sickBedCode = sickBedCode == null ? null : sickBedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sick_room_code
     *
     * @return the value of zmap_h_m1_hospitalize.sick_room_code
     *
     * @mbg.generated
     */
    public String getSickRoomCode() {
        return sickRoomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sick_room_code
     *
     * @param sickRoomCode the value for zmap_h_m1_hospitalize.sick_room_code
     *
     * @mbg.generated
     */
    public void setSickRoomCode(String sickRoomCode) {
        this.sickRoomCode = sickRoomCode == null ? null : sickRoomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.resp_doctor_code
     *
     * @return the value of zmap_h_m1_hospitalize.resp_doctor_code
     *
     * @mbg.generated
     */
    public String getRespDoctorCode() {
        return respDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.resp_doctor_code
     *
     * @param respDoctorCode the value for zmap_h_m1_hospitalize.resp_doctor_code
     *
     * @mbg.generated
     */
    public void setRespDoctorCode(String respDoctorCode) {
        this.respDoctorCode = respDoctorCode == null ? null : respDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.rec_doctor_code
     *
     * @return the value of zmap_h_m1_hospitalize.rec_doctor_code
     *
     * @mbg.generated
     */
    public String getRecDoctorCode() {
        return recDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.rec_doctor_code
     *
     * @param recDoctorCode the value for zmap_h_m1_hospitalize.rec_doctor_code
     *
     * @mbg.generated
     */
    public void setRecDoctorCode(String recDoctorCode) {
        this.recDoctorCode = recDoctorCode == null ? null : recDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.iccard_code
     *
     * @return the value of zmap_h_m1_hospitalize.iccard_code
     *
     * @mbg.generated
     */
    public String getIccardCode() {
        return iccardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.iccard_code
     *
     * @param iccardCode the value for zmap_h_m1_hospitalize.iccard_code
     *
     * @mbg.generated
     */
    public void setIccardCode(String iccardCode) {
        this.iccardCode = iccardCode == null ? null : iccardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.sub_hospital_code
     *
     * @return the value of zmap_h_m1_hospitalize.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_h_m1_hospitalize.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.hospital_code
     *
     * @return the value of zmap_h_m1_hospitalize.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.hospital_code
     *
     * @param hospitalCode the value for zmap_h_m1_hospitalize.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.resp_dept
     *
     * @return the value of zmap_h_m1_hospitalize.resp_dept
     *
     * @mbg.generated
     */
    public String getRespDept() {
        return respDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.resp_dept
     *
     * @param respDept the value for zmap_h_m1_hospitalize.resp_dept
     *
     * @mbg.generated
     */
    public void setRespDept(String respDept) {
        this.respDept = respDept == null ? null : respDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m1_hospitalize.rec_dept_code
     *
     * @return the value of zmap_h_m1_hospitalize.rec_dept_code
     *
     * @mbg.generated
     */
    public String getRecDeptCode() {
        return recDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m1_hospitalize.rec_dept_code
     *
     * @param recDeptCode the value for zmap_h_m1_hospitalize.rec_dept_code
     *
     * @mbg.generated
     */
    public void setRecDeptCode(String recDeptCode) {
        this.recDeptCode = recDeptCode == null ? null : recDeptCode.trim();
    }

	public String getInHosSource() {
		return inHosSource;
	}

	public void setInHosSource(String inHosSource) {
		this.inHosSource = inHosSource;
	}

	public String getInIcd() {
		return inIcd;
	}

	public void setInIcd(String inIcd) {
		this.inIcd = inIcd;
	}

	public String getInIcdName() {
		return inIcdName;
	}

	public void setInIcdName(String inIcdName) {
		this.inIcdName = inIcdName;
	}

	public String getOutIcd() {
		return outIcd;
	}

	public void setOutIcd(String outIcd) {
		this.outIcd = outIcd;
	}

	public String getOutIcdName() {
		return outIcdName;
	}

	public void setOutIcdName(String outIcdName) {
		this.outIcdName = outIcdName;
	}

	public String getInHosFlowCode() {
		return inHosFlowCode;
	}

	public void setInHosFlowCode(String inHosFlowCode) {
		this.inHosFlowCode = inHosFlowCode;
	}
    
}