package com.zmap.zmap.hospitalize.model;

public class ZmapHospitalizeHM2ExamineSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_id
     *
     * @mbg.generated
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.in_hos_code
     *
     * @mbg.generated
     */
    private String inHosCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    private String examFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_time
     *
     * @mbg.generated
     */
    private String examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.zmap_dept_code
     *
     * @mbg.generated
     */
    private String zmapDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    private String examTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_code
     *
     * @mbg.generated
     */
    private String examCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    private String zmapExamCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.exam_result
     *
     * @mbg.generated
     */
    private String examResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_examine.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_id
     *
     * @return the value of zmap_h_m2_examine.exam_id
     *
     * @mbg.generated
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_id
     *
     * @param examId the value for zmap_h_m2_examine.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(String examId) {
        this.examId = examId == null ? null : examId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.in_hos_code
     *
     * @return the value of zmap_h_m2_examine.in_hos_code
     *
     * @mbg.generated
     */
    public String getInHosCode() {
        return inHosCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.in_hos_code
     *
     * @param inHosCode the value for zmap_h_m2_examine.in_hos_code
     *
     * @mbg.generated
     */
    public void setInHosCode(String inHosCode) {
        this.inHosCode = inHosCode == null ? null : inHosCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_flow_code
     *
     * @return the value of zmap_h_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    public String getExamFlowCode() {
        return examFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_flow_code
     *
     * @param examFlowCode the value for zmap_h_m2_examine.exam_flow_code
     *
     * @mbg.generated
     */
    public void setExamFlowCode(String examFlowCode) {
        this.examFlowCode = examFlowCode == null ? null : examFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_time
     *
     * @return the value of zmap_h_m2_examine.exam_time
     *
     * @mbg.generated
     */
    public String getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_time
     *
     * @param examTime the value for zmap_h_m2_examine.exam_time
     *
     * @mbg.generated
     */
    public void setExamTime(String examTime) {
        this.examTime = examTime == null ? null : examTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.sickman_code
     *
     * @return the value of zmap_h_m2_examine.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.sickman_code
     *
     * @param sickmanCode the value for zmap_h_m2_examine.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode == null ? null : sickmanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.doctor_code
     *
     * @return the value of zmap_h_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.doctor_code
     *
     * @param doctorCode the value for zmap_h_m2_examine.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.dept_code
     *
     * @return the value of zmap_h_m2_examine.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.dept_code
     *
     * @param deptCode the value for zmap_h_m2_examine.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.zmap_dept_code
     *
     * @return the value of zmap_h_m2_examine.zmap_dept_code
     *
     * @mbg.generated
     */
    public String getZmapDeptCode() {
        return zmapDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.zmap_dept_code
     *
     * @param zmapDeptCode the value for zmap_h_m2_examine.zmap_dept_code
     *
     * @mbg.generated
     */
    public void setZmapDeptCode(String zmapDeptCode) {
        this.zmapDeptCode = zmapDeptCode == null ? null : zmapDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_type_code
     *
     * @return the value of zmap_h_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    public String getExamTypeCode() {
        return examTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_type_code
     *
     * @param examTypeCode the value for zmap_h_m2_examine.exam_type_code
     *
     * @mbg.generated
     */
    public void setExamTypeCode(String examTypeCode) {
        this.examTypeCode = examTypeCode == null ? null : examTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_code
     *
     * @return the value of zmap_h_m2_examine.exam_code
     *
     * @mbg.generated
     */
    public String getExamCode() {
        return examCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_code
     *
     * @param examCode the value for zmap_h_m2_examine.exam_code
     *
     * @mbg.generated
     */
    public void setExamCode(String examCode) {
        this.examCode = examCode == null ? null : examCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.zmap_exam_code
     *
     * @return the value of zmap_h_m2_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    public String getZmapExamCode() {
        return zmapExamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.zmap_exam_code
     *
     * @param zmapExamCode the value for zmap_h_m2_examine.zmap_exam_code
     *
     * @mbg.generated
     */
    public void setZmapExamCode(String zmapExamCode) {
        this.zmapExamCode = zmapExamCode == null ? null : zmapExamCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.exam_result
     *
     * @return the value of zmap_h_m2_examine.exam_result
     *
     * @mbg.generated
     */
    public String getExamResult() {
        return examResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.exam_result
     *
     * @param examResult the value for zmap_h_m2_examine.exam_result
     *
     * @mbg.generated
     */
    public void setExamResult(String examResult) {
        this.examResult = examResult == null ? null : examResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.sub_hospital_code
     *
     * @return the value of zmap_h_m2_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_h_m2_examine.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_examine.hospital_code
     *
     * @return the value of zmap_h_m2_examine.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_examine.hospital_code
     *
     * @param hospitalCode the value for zmap_h_m2_examine.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}