package com.zmap.zmap.hospitalize.model;

public class ZmapHospitalizeHM2DrugUseSyncModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    private String drugUseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.in_hos_code
     *
     * @mbg.generated
     */
    private String inHosCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    private String drugUseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    private String drugUseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.zmap_dept_code
     *
     * @mbg.generated
     */
    private String zmapDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    private String drugTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    private String drugCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.zmap_drug_code
     *
     * @mbg.generated
     */
    private String zmapDrugCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    private String drugDose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    private String useFreq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_drug_use.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_use_id
     *
     * @return the value of zmap_h_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    public String getDrugUseId() {
        return drugUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_use_id
     *
     * @param drugUseId the value for zmap_h_m2_drug_use.drug_use_id
     *
     * @mbg.generated
     */
    public void setDrugUseId(String drugUseId) {
        this.drugUseId = drugUseId == null ? null : drugUseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.in_hos_code
     *
     * @return the value of zmap_h_m2_drug_use.in_hos_code
     *
     * @mbg.generated
     */
    public String getInHosCode() {
        return inHosCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.in_hos_code
     *
     * @param inHosCode the value for zmap_h_m2_drug_use.in_hos_code
     *
     * @mbg.generated
     */
    public void setInHosCode(String inHosCode) {
        this.inHosCode = inHosCode == null ? null : inHosCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_use_code
     *
     * @return the value of zmap_h_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    public String getDrugUseCode() {
        return drugUseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_use_code
     *
     * @param drugUseCode the value for zmap_h_m2_drug_use.drug_use_code
     *
     * @mbg.generated
     */
    public void setDrugUseCode(String drugUseCode) {
        this.drugUseCode = drugUseCode == null ? null : drugUseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_use_time
     *
     * @return the value of zmap_h_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    public String getDrugUseTime() {
        return drugUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_use_time
     *
     * @param drugUseTime the value for zmap_h_m2_drug_use.drug_use_time
     *
     * @mbg.generated
     */
    public void setDrugUseTime(String drugUseTime) {
        this.drugUseTime = drugUseTime == null ? null : drugUseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.sickman_code
     *
     * @return the value of zmap_h_m2_drug_use.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.sickman_code
     *
     * @param sickmanCode the value for zmap_h_m2_drug_use.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode == null ? null : sickmanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.doctor_code
     *
     * @return the value of zmap_h_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.doctor_code
     *
     * @param doctorCode the value for zmap_h_m2_drug_use.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.dept_code
     *
     * @return the value of zmap_h_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.dept_code
     *
     * @param deptCode the value for zmap_h_m2_drug_use.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.zmap_dept_code
     *
     * @return the value of zmap_h_m2_drug_use.zmap_dept_code
     *
     * @mbg.generated
     */
    public String getZmapDeptCode() {
        return zmapDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.zmap_dept_code
     *
     * @param zmapDeptCode the value for zmap_h_m2_drug_use.zmap_dept_code
     *
     * @mbg.generated
     */
    public void setZmapDeptCode(String zmapDeptCode) {
        this.zmapDeptCode = zmapDeptCode == null ? null : zmapDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_type_code
     *
     * @return the value of zmap_h_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    public String getDrugTypeCode() {
        return drugTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_type_code
     *
     * @param drugTypeCode the value for zmap_h_m2_drug_use.drug_type_code
     *
     * @mbg.generated
     */
    public void setDrugTypeCode(String drugTypeCode) {
        this.drugTypeCode = drugTypeCode == null ? null : drugTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_code
     *
     * @return the value of zmap_h_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_code
     *
     * @param drugCode the value for zmap_h_m2_drug_use.drug_code
     *
     * @mbg.generated
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode == null ? null : drugCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.zmap_drug_code
     *
     * @return the value of zmap_h_m2_drug_use.zmap_drug_code
     *
     * @mbg.generated
     */
    public String getZmapDrugCode() {
        return zmapDrugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.zmap_drug_code
     *
     * @param zmapDrugCode the value for zmap_h_m2_drug_use.zmap_drug_code
     *
     * @mbg.generated
     */
    public void setZmapDrugCode(String zmapDrugCode) {
        this.zmapDrugCode = zmapDrugCode == null ? null : zmapDrugCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.drug_dose
     *
     * @return the value of zmap_h_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    public String getDrugDose() {
        return drugDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.drug_dose
     *
     * @param drugDose the value for zmap_h_m2_drug_use.drug_dose
     *
     * @mbg.generated
     */
    public void setDrugDose(String drugDose) {
        this.drugDose = drugDose == null ? null : drugDose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.use_freq
     *
     * @return the value of zmap_h_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    public String getUseFreq() {
        return useFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.use_freq
     *
     * @param useFreq the value for zmap_h_m2_drug_use.use_freq
     *
     * @mbg.generated
     */
    public void setUseFreq(String useFreq) {
        this.useFreq = useFreq == null ? null : useFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.sub_hospital_code
     *
     * @return the value of zmap_h_m2_drug_use.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_h_m2_drug_use.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_drug_use.hospital_code
     *
     * @return the value of zmap_h_m2_drug_use.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_drug_use.hospital_code
     *
     * @param hospitalCode the value for zmap_h_m2_drug_use.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}