package com.zmap.zmap.hospitalize.model;

import java.math.BigDecimal;

public class ZmapHospitalizeHM2ChargeSyncModel {
    
	private String settleAcctCode;
	private String settleTypeCode;
	private String isInsureSettle;
	private String acctItemCode;
	private String settleChargeTime;
	private String insureSettleTime;
	private BigDecimal recAmount;
	private String morderCode;
	private String inHosFlowCode;
	
	
	
	public String getInHosFlowCode() {
		return inHosFlowCode;
	}

	public void setInHosFlowCode(String inHosFlowCode) {
		this.inHosFlowCode = inHosFlowCode;
	}

	public String getMorderCode() {
		return morderCode;
	}

	public void setMorderCode(String morderCode) {
		this.morderCode = morderCode;
	}

	public String getSettleChargeTime() {
		return settleChargeTime;
	}

	public void setSettleChargeTime(String settleChargeTime) {
		this.settleChargeTime = settleChargeTime;
	}

	public String getInsureSettleTime() {
		return insureSettleTime;
	}

	public void setInsureSettleTime(String insureSettleTime) {
		this.insureSettleTime = insureSettleTime;
	}

	public BigDecimal getRecAmount() {
		return recAmount;
	}

	public void setRecAmount(BigDecimal recAmount) {
		this.recAmount = recAmount;
	}

	public String getAcctItemCode() {
		return acctItemCode;
	}

	public void setAcctItemCode(String acctItemCode) {
		this.acctItemCode = acctItemCode;
	}

	public String getIsInsureSettle() {
		return isInsureSettle;
	}

	public void setIsInsureSettle(String isInsureSettle) {
		this.isInsureSettle = isInsureSettle;
	}


	public String getSettleAcctCode() {
		return settleAcctCode;
	}

	public void setSettleAcctCode(String settleAcctCode) {
		this.settleAcctCode = settleAcctCode;
	}

	public String getSettleTypeCode() {
		return settleTypeCode;
	}

	public void setSettleTypeCode(String settleTypeCode) {
		this.settleTypeCode = settleTypeCode;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.sick_fee_flow_id
     *
     * @mbg.generated
     */
    private String sickFeeFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.in_hos_code
     *
     * @mbg.generated
     */
    private String inHosCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.sick_fee_flow_code
     *
     * @mbg.generated
     */
    private String sickFeeFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.sickman_code
     *
     * @mbg.generated
     */
    private String sickmanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.zmap_dept_code
     *
     * @mbg.generated
     */
    private String zmapDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.fee_date
     *
     * @mbg.generated
     */
    private String feeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    private String feeSourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    private String feeClassCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.fee_type_code
     *
     * @mbg.generated
     */
    private String feeTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.zmap_fee_item_code
     *
     * @mbg.generated
     */
    private String zmapFeeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    private String feeItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.num
     *
     * @mbg.generated
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.unit_price
     *
     * @mbg.generated
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.dis_price
     *
     * @mbg.generated
     */
    private BigDecimal disPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.dis_ratio
     *
     * @mbg.generated
     */
    private String disRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.phar_code
     *
     * @mbg.generated
     */
    private String pharCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.sub_hospital_code
     *
     * @mbg.generated
     */
    private String subHospitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmap_h_m2_charge.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.sick_fee_flow_id
     *
     * @return the value of zmap_h_m2_charge.sick_fee_flow_id
     *
     * @mbg.generated
     */
    public String getSickFeeFlowId() {
        return sickFeeFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.sick_fee_flow_id
     *
     * @param sickFeeFlowId the value for zmap_h_m2_charge.sick_fee_flow_id
     *
     * @mbg.generated
     */
    public void setSickFeeFlowId(String sickFeeFlowId) {
        this.sickFeeFlowId = sickFeeFlowId == null ? null : sickFeeFlowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.in_hos_code
     *
     * @return the value of zmap_h_m2_charge.in_hos_code
     *
     * @mbg.generated
     */
    public String getInHosCode() {
        return inHosCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.in_hos_code
     *
     * @param inHosCode the value for zmap_h_m2_charge.in_hos_code
     *
     * @mbg.generated
     */
    public void setInHosCode(String inHosCode) {
        this.inHosCode = inHosCode == null ? null : inHosCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.sick_fee_flow_code
     *
     * @return the value of zmap_h_m2_charge.sick_fee_flow_code
     *
     * @mbg.generated
     */
    public String getSickFeeFlowCode() {
        return sickFeeFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.sick_fee_flow_code
     *
     * @param sickFeeFlowCode the value for zmap_h_m2_charge.sick_fee_flow_code
     *
     * @mbg.generated
     */
    public void setSickFeeFlowCode(String sickFeeFlowCode) {
        this.sickFeeFlowCode = sickFeeFlowCode == null ? null : sickFeeFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.sickman_code
     *
     * @return the value of zmap_h_m2_charge.sickman_code
     *
     * @mbg.generated
     */
    public String getSickmanCode() {
        return sickmanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.sickman_code
     *
     * @param sickmanCode the value for zmap_h_m2_charge.sickman_code
     *
     * @mbg.generated
     */
    public void setSickmanCode(String sickmanCode) {
        this.sickmanCode = sickmanCode == null ? null : sickmanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.doctor_code
     *
     * @return the value of zmap_h_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.doctor_code
     *
     * @param doctorCode the value for zmap_h_m2_charge.doctor_code
     *
     * @mbg.generated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.dept_code
     *
     * @return the value of zmap_h_m2_charge.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.dept_code
     *
     * @param deptCode the value for zmap_h_m2_charge.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.zmap_dept_code
     *
     * @return the value of zmap_h_m2_charge.zmap_dept_code
     *
     * @mbg.generated
     */
    public String getZmapDeptCode() {
        return zmapDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.zmap_dept_code
     *
     * @param zmapDeptCode the value for zmap_h_m2_charge.zmap_dept_code
     *
     * @mbg.generated
     */
    public void setZmapDeptCode(String zmapDeptCode) {
        this.zmapDeptCode = zmapDeptCode == null ? null : zmapDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.fee_date
     *
     * @return the value of zmap_h_m2_charge.fee_date
     *
     * @mbg.generated
     */
    public String getFeeDate() {
        return feeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.fee_date
     *
     * @param feeDate the value for zmap_h_m2_charge.fee_date
     *
     * @mbg.generated
     */
    public void setFeeDate(String feeDate) {
        this.feeDate = feeDate == null ? null : feeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.fee_source_code
     *
     * @return the value of zmap_h_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    public String getFeeSourceCode() {
        return feeSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.fee_source_code
     *
     * @param feeSourceCode the value for zmap_h_m2_charge.fee_source_code
     *
     * @mbg.generated
     */
    public void setFeeSourceCode(String feeSourceCode) {
        this.feeSourceCode = feeSourceCode == null ? null : feeSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.fee_class_code
     *
     * @return the value of zmap_h_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    public String getFeeClassCode() {
        return feeClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.fee_class_code
     *
     * @param feeClassCode the value for zmap_h_m2_charge.fee_class_code
     *
     * @mbg.generated
     */
    public void setFeeClassCode(String feeClassCode) {
        this.feeClassCode = feeClassCode == null ? null : feeClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.fee_type_code
     *
     * @return the value of zmap_h_m2_charge.fee_type_code
     *
     * @mbg.generated
     */
    public String getFeeTypeCode() {
        return feeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.fee_type_code
     *
     * @param feeTypeCode the value for zmap_h_m2_charge.fee_type_code
     *
     * @mbg.generated
     */
    public void setFeeTypeCode(String feeTypeCode) {
        this.feeTypeCode = feeTypeCode == null ? null : feeTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.zmap_fee_item_code
     *
     * @return the value of zmap_h_m2_charge.zmap_fee_item_code
     *
     * @mbg.generated
     */
    public String getZmapFeeItemCode() {
        return zmapFeeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.zmap_fee_item_code
     *
     * @param zmapFeeItemCode the value for zmap_h_m2_charge.zmap_fee_item_code
     *
     * @mbg.generated
     */
    public void setZmapFeeItemCode(String zmapFeeItemCode) {
        this.zmapFeeItemCode = zmapFeeItemCode == null ? null : zmapFeeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.fee_item_code
     *
     * @return the value of zmap_h_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    public String getFeeItemCode() {
        return feeItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.fee_item_code
     *
     * @param feeItemCode the value for zmap_h_m2_charge.fee_item_code
     *
     * @mbg.generated
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode == null ? null : feeItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.size
     *
     * @return the value of zmap_h_m2_charge.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.size
     *
     * @param size the value for zmap_h_m2_charge.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.unit
     *
     * @return the value of zmap_h_m2_charge.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.unit
     *
     * @param unit the value for zmap_h_m2_charge.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.num
     *
     * @return the value of zmap_h_m2_charge.num
     *
     * @mbg.generated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.num
     *
     * @param num the value for zmap_h_m2_charge.num
     *
     * @mbg.generated
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.unit_price
     *
     * @return the value of zmap_h_m2_charge.unit_price
     *
     * @mbg.generated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.unit_price
     *
     * @param unitPrice the value for zmap_h_m2_charge.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.dis_price
     *
     * @return the value of zmap_h_m2_charge.dis_price
     *
     * @mbg.generated
     */
    public BigDecimal getDisPrice() {
        return disPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.dis_price
     *
     * @param disPrice the value for zmap_h_m2_charge.dis_price
     *
     * @mbg.generated
     */
    public void setDisPrice(BigDecimal disPrice) {
        this.disPrice = disPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.dis_ratio
     *
     * @return the value of zmap_h_m2_charge.dis_ratio
     *
     * @mbg.generated
     */
    public String getDisRatio() {
        return disRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.dis_ratio
     *
     * @param disRatio the value for zmap_h_m2_charge.dis_ratio
     *
     * @mbg.generated
     */
    public void setDisRatio(String disRatio) {
        this.disRatio = disRatio == null ? null : disRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.amount
     *
     * @return the value of zmap_h_m2_charge.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.amount
     *
     * @param amount the value for zmap_h_m2_charge.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.phar_code
     *
     * @return the value of zmap_h_m2_charge.phar_code
     *
     * @mbg.generated
     */
    public String getPharCode() {
        return pharCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.phar_code
     *
     * @param pharCode the value for zmap_h_m2_charge.phar_code
     *
     * @mbg.generated
     */
    public void setPharCode(String pharCode) {
        this.pharCode = pharCode == null ? null : pharCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.sub_hospital_code
     *
     * @return the value of zmap_h_m2_charge.sub_hospital_code
     *
     * @mbg.generated
     */
    public String getSubHospitalCode() {
        return subHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.sub_hospital_code
     *
     * @param subHospitalCode the value for zmap_h_m2_charge.sub_hospital_code
     *
     * @mbg.generated
     */
    public void setSubHospitalCode(String subHospitalCode) {
        this.subHospitalCode = subHospitalCode == null ? null : subHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmap_h_m2_charge.hospital_code
     *
     * @return the value of zmap_h_m2_charge.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmap_h_m2_charge.hospital_code
     *
     * @param hospitalCode the value for zmap_h_m2_charge.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}