package com.zmap.zmap.framework.base.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.framework.base.model.ZmapLOperationModel;
@Mapper
public interface ZmapLOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    int insert(ZmapLOperationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    int insertSelective(ZmapLOperationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    ZmapLOperationModel selectByPrimaryKey(String operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapLOperationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapLOperationModel record);
    ZmapLOperationModel selectByHisPrimaryKey(ZmapLOperationModel record);
    int deleteByHisPrimaryKey(ZmapLOperationModel record);
}