package com.zmap.zmap.framework.base.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.framework.base.model.ZmapRDoctorModel;
@Mapper
public interface ZmapRDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    int insert(ZmapRDoctorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    int insertSelective(ZmapRDoctorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    ZmapRDoctorModel selectByPrimaryKey(String doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZmapRDoctorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_r_doctor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmapRDoctorModel record);
    
    ZmapRDoctorModel selectByHisPrimaryKey(ZmapRDoctorModel record);//根据his库的业务主键判断是否已存在
    int deleteByHisPrimaryKey(ZmapRDoctorModel record);
    int batchInsert(List<ZmapRDoctorModel> record);//批量插入
    
    List<ZmapRDoctorModel> selectDoctorsByDoctorCodes(HashMap params);
}