package com.zmap.zmap.framework.base.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zmap.zmap.framework.base.model.ZmapLAcctItemModel;

@Mapper
public interface ZmapLAcctItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_acct_item
     *
     * @mbg.generated
     */
    int insert(ZmapLAcctItemModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmap_l_acct_item
     *
     * @mbg.generated
     */
    int insertSelective(ZmapLAcctItemModel record);
    ZmapLAcctItemModel selectByHisPrimaryKey(ZmapLAcctItemModel record);
    int deleteByHisPrimaryKey(ZmapLAcctItemModel record);
}